/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: aceerr.i

package openace

const ECA_SUCCESS uint = 0
const ECA_ALLOCATION_FAILED uint = 5001
const ECA_INSUFFICIENT_BUFFER uint = 5005
const ECA_INVALID_FIELDDEF uint = 5012
const ECA_INVALID_FILTER_OPTION uint = 5013
const ECA_INVALID_INDEX_HANDLE uint = 5014
const ECA_INVALID_INDEX_NAME uint = 5015
const ECA_INVALID_INDEX_ORDER_NAME uint = 5016
const ECA_INVALID_OPTION uint = 5019
const ECA_INVALID_TABLE_HANDLE uint = 5023
const ECA_INVALID_FIELDNAME uint = 5032
const ECA_LOCK_FAILED uint = 5035
const ECA_NO_TABLE uint = 5039
const ECA_UNKNOWN_ERRCODE uint = 5048
const ECA_TABLE_CLOSED_IN_TRANSACTION uint = 5053
const ECA_TABLE_NOT_EXCLUSIVE uint = 5067
const ECA_NO_CURRENT_RECORD uint = 5068
const ECA_RECORD_NOT_LOCKED uint = 5069
const ECA_LOCK_REQUIRED uint = 5069
const ECA_INVALID_DATA_TYPE uint = 5070
const ECA_CORRUPT_INDEX uint = 5088
const ECA_INVALID_VALUE uint = 5101
const ECA_OPEN_ERROR uint = 5159
const ECA_CANNOT_OPEN_DATABASE_TABLE uint = 5159
