/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: openace.i

package openace

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stddef.h>
#include <stdint.h>


typedef ptrdiff_t intgo;
typedef size_t uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
typedef _gostring_ swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef _gostring_ swig_type_7;
typedef _gostring_ swig_type_8;
typedef _gostring_ swig_type_9;
typedef _gostring_ swig_type_10;
typedef _gostring_ swig_type_11;
typedef _gostring_ swig_type_12;
typedef _gostring_ swig_type_13;
typedef _gostring_ swig_type_14;
typedef _gostring_ swig_type_15;
typedef _gostring_ swig_type_16;
typedef _gostring_ swig_type_17;
typedef _gostring_ swig_type_18;
typedef _gostring_ swig_type_19;
typedef _gostring_ swig_type_20;
typedef _gostring_ swig_type_21;
typedef _gostring_ swig_type_22;
typedef _gostring_ swig_type_23;
typedef _gostring_ swig_type_24;
typedef _gostring_ swig_type_25;
typedef _gostring_ swig_type_26;
typedef _gostring_ swig_type_27;
typedef _gostring_ swig_type_28;
typedef _gostring_ swig_type_29;
typedef _gostring_ swig_type_30;
typedef _gostring_ swig_type_31;
typedef _gostring_ swig_type_32;
typedef _gostring_ swig_type_33;
typedef _gostring_ swig_type_34;
typedef _gostring_ swig_type_35;
typedef _gostring_ swig_type_36;
typedef _gostring_ swig_type_37;
typedef _gostring_ swig_type_38;
typedef _gostring_ swig_type_39;
typedef _gostring_ swig_type_40;
typedef _gostring_ swig_type_41;
typedef _gostring_ swig_type_42;
typedef _gostring_ swig_type_43;
typedef _gostring_ swig_type_44;
typedef _gostring_ swig_type_45;
typedef _gostring_ swig_type_46;
typedef _gostring_ swig_type_47;
typedef _gostring_ swig_type_48;
typedef _gostring_ swig_type_49;
typedef _gostring_ swig_type_50;
typedef _gostring_ swig_type_51;
typedef _gostring_ swig_type_52;
typedef _gostring_ swig_type_53;
typedef _gostring_ swig_type_54;
typedef _gostring_ swig_type_55;
typedef _gostring_ swig_type_56;
typedef _gostring_ swig_type_57;
typedef _gostring_ swig_type_58;
typedef _gostring_ swig_type_59;
typedef _gostring_ swig_type_60;
typedef _gostring_ swig_type_61;
typedef _gostring_ swig_type_62;
typedef _gostring_ swig_type_63;
typedef _gostring_ swig_type_64;
typedef _gostring_ swig_type_65;
extern void _wrap_Swig_free_openace_035495a50e9dd2d9(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_openace_035495a50e9dd2d9(swig_intgo arg1);
extern void _wrap_HB_ACEDATA_ulLastError_set_openace_035495a50e9dd2d9(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_HB_ACEDATA_ulLastError_get_openace_035495a50e9dd2d9(uintptr_t arg1);
extern void _wrap_HB_ACEDATA_bErrSeq_set_openace_035495a50e9dd2d9(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_HB_ACEDATA_bErrSeq_get_openace_035495a50e9dd2d9(uintptr_t arg1);
extern void _wrap_HB_ACEDATA_bRTEOnce_set_openace_035495a50e9dd2d9(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_HB_ACEDATA_bRTEOnce_get_openace_035495a50e9dd2d9(uintptr_t arg1);
extern void _wrap_HB_ACEDATA_szRTE_set_openace_035495a50e9dd2d9(uintptr_t arg1, swig_type_1 arg2);
extern swig_type_2 _wrap_HB_ACEDATA_szRTE_get_openace_035495a50e9dd2d9(uintptr_t arg1);
extern void _wrap_HB_ACEDATA_bXPPEatSlash_set_openace_035495a50e9dd2d9(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_HB_ACEDATA_bXPPEatSlash_get_openace_035495a50e9dd2d9(uintptr_t arg1);
extern void _wrap_HB_ACEDATA_szDbCdp_set_openace_035495a50e9dd2d9(uintptr_t arg1, swig_type_3 arg2);
extern swig_type_4 _wrap_HB_ACEDATA_szDbCdp_get_openace_035495a50e9dd2d9(uintptr_t arg1);
extern void _wrap_HB_ACEDATA_szVirtualPathCut_set_openace_035495a50e9dd2d9(uintptr_t arg1, swig_type_5 arg2);
extern swig_type_6 _wrap_HB_ACEDATA_szVirtualPathCut_get_openace_035495a50e9dd2d9(uintptr_t arg1);
extern void _wrap_HB_ACEDATA_nVirtualPathLen_set_openace_035495a50e9dd2d9(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_HB_ACEDATA_nVirtualPathLen_get_openace_035495a50e9dd2d9(uintptr_t arg1);
extern void _wrap_HB_ACEDATA_pCBTrace_set_openace_035495a50e9dd2d9(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_HB_ACEDATA_pCBTrace_get_openace_035495a50e9dd2d9(uintptr_t arg1);
extern void _wrap_HB_ACEDATA_pCBOnRTE_set_openace_035495a50e9dd2d9(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_HB_ACEDATA_pCBOnRTE_get_openace_035495a50e9dd2d9(uintptr_t arg1);
extern uintptr_t _wrap_new_HB_ACEDATA_openace_035495a50e9dd2d9(void);
extern void _wrap_delete_HB_ACEDATA_openace_035495a50e9dd2d9(uintptr_t arg1);
extern void _wrap_ACE_MGMT_INSTALL_INFO_ulUserOption_set_openace_035495a50e9dd2d9(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_ACE_MGMT_INSTALL_INFO_ulUserOption_get_openace_035495a50e9dd2d9(uintptr_t arg1);
extern void _wrap_ACE_MGMT_INSTALL_INFO_aucRegisteredOwner_set_openace_035495a50e9dd2d9(uintptr_t arg1, swig_type_7 arg2);
extern swig_type_8 _wrap_ACE_MGMT_INSTALL_INFO_aucRegisteredOwner_get_openace_035495a50e9dd2d9(uintptr_t arg1);
extern void _wrap_ACE_MGMT_INSTALL_INFO_aucVersionStr_set_openace_035495a50e9dd2d9(uintptr_t arg1, swig_type_9 arg2);
extern swig_type_10 _wrap_ACE_MGMT_INSTALL_INFO_aucVersionStr_get_openace_035495a50e9dd2d9(uintptr_t arg1);
extern void _wrap_ACE_MGMT_INSTALL_INFO_aucInstallDate_set_openace_035495a50e9dd2d9(uintptr_t arg1, swig_type_11 arg2);
extern swig_type_12 _wrap_ACE_MGMT_INSTALL_INFO_aucInstallDate_get_openace_035495a50e9dd2d9(uintptr_t arg1);
extern void _wrap_ACE_MGMT_INSTALL_INFO_aucOemCharName_set_openace_035495a50e9dd2d9(uintptr_t arg1, swig_type_13 arg2);
extern swig_type_14 _wrap_ACE_MGMT_INSTALL_INFO_aucOemCharName_get_openace_035495a50e9dd2d9(uintptr_t arg1);
extern void _wrap_ACE_MGMT_INSTALL_INFO_aucAnsiCharName_set_openace_035495a50e9dd2d9(uintptr_t arg1, swig_type_15 arg2);
extern swig_type_16 _wrap_ACE_MGMT_INSTALL_INFO_aucAnsiCharName_get_openace_035495a50e9dd2d9(uintptr_t arg1);
extern void _wrap_ACE_MGMT_INSTALL_INFO_aucEvalExpireDate_set_openace_035495a50e9dd2d9(uintptr_t arg1, swig_type_17 arg2);
extern swig_type_18 _wrap_ACE_MGMT_INSTALL_INFO_aucEvalExpireDate_get_openace_035495a50e9dd2d9(uintptr_t arg1);
extern void _wrap_ACE_MGMT_INSTALL_INFO_aucSerialNumber_set_openace_035495a50e9dd2d9(uintptr_t arg1, swig_type_19 arg2);
extern swig_type_20 _wrap_ACE_MGMT_INSTALL_INFO_aucSerialNumber_get_openace_035495a50e9dd2d9(uintptr_t arg1);
extern void _wrap_ACE_MGMT_INSTALL_INFO_ulMaxStatefulUsers_set_openace_035495a50e9dd2d9(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_ACE_MGMT_INSTALL_INFO_ulMaxStatefulUsers_get_openace_035495a50e9dd2d9(uintptr_t arg1);
extern void _wrap_ACE_MGMT_INSTALL_INFO_ulMaxStatelessUsers_set_openace_035495a50e9dd2d9(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_ACE_MGMT_INSTALL_INFO_ulMaxStatelessUsers_get_openace_035495a50e9dd2d9(uintptr_t arg1);
extern uintptr_t _wrap_new_ACE_MGMT_INSTALL_INFO_openace_035495a50e9dd2d9(void);
extern void _wrap_delete_ACE_MGMT_INSTALL_INFO_openace_035495a50e9dd2d9(uintptr_t arg1);
extern swig_intgo _wrap_SysSetTable_openace_035495a50e9dd2d9(swig_voidp arg1, swig_intgo arg2, uintptr_t arg3, swig_type_21 arg4);
extern swig_intgo _wrap_SetCallbackOnRTE_openace_035495a50e9dd2d9(uintptr_t arg1);
extern swig_intgo _wrap_SetCallbackTrace_openace_035495a50e9dd2d9(uintptr_t arg1);
extern swig_intgo _wrap_AddCustomKey_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_AppendRecord_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_ApplicationExit_openace_035495a50e9dd2d9(void);
extern swig_intgo _wrap_AtBOF_openace_035495a50e9dd2d9(swig_intgo arg1, swig_voidp arg2);
extern swig_intgo _wrap_AtEOF_openace_035495a50e9dd2d9(swig_intgo arg1, swig_voidp arg2);
extern swig_intgo _wrap_CacheRecords_openace_035495a50e9dd2d9(swig_intgo arg1, short arg2);
extern swig_intgo _wrap_BeginTransaction_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_ClearFilter_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_ClearProgressCallback_openace_035495a50e9dd2d9(void);
extern swig_intgo _wrap_ClearRelation_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_ClearScope_openace_035495a50e9dd2d9(swig_intgo arg1, short arg2);
extern swig_intgo _wrap_CloseAllIndexes_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_CloseIndex_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_CloseTable_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_CommitTransaction_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_Connect_openace_035495a50e9dd2d9(swig_type_22 arg1, swig_voidp arg2);
extern swig_intgo _wrap_CopyTableContents_openace_035495a50e9dd2d9(swig_intgo arg1, swig_intgo arg2, short arg3);
extern swig_intgo _wrap_CreateIndex_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_23 arg2, swig_type_24 arg3, swig_type_25 arg4, swig_type_26 arg5, swig_type_27 arg6, swig_intgo arg7, swig_voidp arg8);
extern swig_intgo _wrap_CreateTable_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_28 arg2, swig_type_29 arg3, short arg4, short arg5, short arg6, short arg7, short arg8, swig_type_30 arg9, swig_voidp arg10);
extern swig_intgo _wrap_DeleteCustomKey_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_DeleteIndex_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_DeleteRecord_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_Disconnect_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_ExtractKey_openace_035495a50e9dd2d9(swig_intgo arg1, uintptr_t arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetAllIndexes_openace_035495a50e9dd2d9(swig_intgo arg1, swig_voidp arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetAllLocks_openace_035495a50e9dd2d9(swig_intgo arg1, swig_voidp arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetBinary_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_31 arg2, swig_intgo arg3, uintptr_t arg4, swig_voidp arg5);
extern swig_intgo _wrap_GetBinaryLength_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_32 arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetDateFormat_openace_035495a50e9dd2d9(uintptr_t arg1, swig_voidp arg2);
extern swig_intgo _wrap_GetDouble_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_33 arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetErrorString_openace_035495a50e9dd2d9(swig_intgo arg1, uintptr_t arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetField_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_34 arg2, uintptr_t arg3, swig_voidp arg4, short arg5);
extern swig_intgo _wrap_GetFieldDecimals_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_35 arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetFieldLength_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_36 arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetFieldName_openace_035495a50e9dd2d9(swig_intgo arg1, short arg2, uintptr_t arg3, swig_voidp arg4);
extern swig_intgo _wrap_GetFieldType_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_37 arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetHandleType_openace_035495a50e9dd2d9(swig_intgo arg1, swig_voidp arg2);
extern swig_intgo _wrap_GetIndexCondition_openace_035495a50e9dd2d9(swig_intgo arg1, uintptr_t arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetIndexExpr_openace_035495a50e9dd2d9(swig_intgo arg1, uintptr_t arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetIndexFilename_openace_035495a50e9dd2d9(swig_intgo arg1, short arg2, uintptr_t arg3, swig_voidp arg4);
extern swig_intgo _wrap_GetIndexName_openace_035495a50e9dd2d9(swig_intgo arg1, uintptr_t arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetIndexHandle_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_38 arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetIndexHandleByOrder_openace_035495a50e9dd2d9(swig_intgo arg1, short arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetJulian_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_39 arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetKeyCount_openace_035495a50e9dd2d9(swig_intgo arg1, short arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetKeyLength_openace_035495a50e9dd2d9(swig_intgo arg1, swig_voidp arg2);
extern swig_intgo _wrap_GetKeyNum_openace_035495a50e9dd2d9(swig_intgo arg1, short arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetKeyType_openace_035495a50e9dd2d9(swig_intgo arg1, swig_voidp arg2);
extern swig_intgo _wrap_GetLastError_openace_035495a50e9dd2d9(swig_voidp arg1, uintptr_t arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetLastTableUpdate_openace_035495a50e9dd2d9(swig_intgo arg1, uintptr_t arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetLogical_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_40 arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetMemoLength_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_41 arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetMilliseconds_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_42 arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetNumFields_openace_035495a50e9dd2d9(swig_intgo arg1, swig_voidp arg2);
extern swig_intgo _wrap_GetNumIndexes_openace_035495a50e9dd2d9(swig_intgo arg1, swig_voidp arg2);
extern swig_intgo _wrap_GetNumLocks_openace_035495a50e9dd2d9(swig_intgo arg1, swig_voidp arg2);
extern swig_intgo _wrap_GetRecordCount_openace_035495a50e9dd2d9(swig_intgo arg1, short arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetRecordNum_openace_035495a50e9dd2d9(swig_intgo arg1, short arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetRecordLength_openace_035495a50e9dd2d9(swig_intgo arg1, swig_voidp arg2);
extern swig_intgo _wrap_GetRelKeyPos_openace_035495a50e9dd2d9(swig_intgo arg1, swig_voidp arg2);
extern swig_intgo _wrap_GetServerName_openace_035495a50e9dd2d9(swig_intgo arg1, uintptr_t arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetString_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_43 arg2, uintptr_t arg3, swig_voidp arg4, short arg5);
extern swig_intgo _wrap_GetTableAlias_openace_035495a50e9dd2d9(swig_intgo arg1, uintptr_t arg2, swig_voidp arg3);
extern swig_intgo _wrap_GetTableFilename_openace_035495a50e9dd2d9(swig_intgo arg1, short arg2, uintptr_t arg3, swig_voidp arg4);
extern swig_intgo _wrap_GetTableType_openace_035495a50e9dd2d9(swig_intgo arg1, swig_voidp arg2);
extern swig_intgo _wrap_GotoBottom_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_GotoRecord_openace_035495a50e9dd2d9(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_GotoTop_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_IsEmpty_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_44 arg2, swig_voidp arg3);
extern swig_intgo _wrap_IsIndexDescending_openace_035495a50e9dd2d9(swig_intgo arg1, swig_voidp arg2);
extern swig_intgo _wrap_IsIndexUnique_openace_035495a50e9dd2d9(swig_intgo arg1, swig_voidp arg2);
extern swig_intgo _wrap_IsRecordDeleted_openace_035495a50e9dd2d9(swig_intgo arg1, swig_voidp arg2);
extern swig_intgo _wrap_LockRecord_openace_035495a50e9dd2d9(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_LockTable_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_MgConnect_openace_035495a50e9dd2d9(swig_type_45 arg1, swig_type_46 arg2, swig_type_47 arg3, swig_voidp arg4);
extern swig_intgo _wrap_MgDisconnect_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_MgGetInstallInfo_openace_035495a50e9dd2d9(swig_intgo arg1, uintptr_t arg2, swig_voidp arg3);
extern swig_intgo _wrap_MgGetServerType_openace_035495a50e9dd2d9(swig_intgo arg1, swig_voidp arg2);
extern swig_intgo _wrap_NullTerminateStrings_openace_035495a50e9dd2d9(short arg1);
extern swig_intgo _wrap_OpenIndex_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_48 arg2, swig_voidp arg3, swig_voidp arg4);
extern swig_intgo _wrap_OpenTable_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_49 arg2, swig_type_50 arg3, short arg4, short arg5, short arg6, short arg7, swig_intgo arg8, swig_voidp arg9);
extern swig_intgo _wrap_PackTable_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_RecallRecord_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_RefreshRecord_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_Reindex_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_RollbackTransaction_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_Seek_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_51 arg2, short arg3, short arg4, short arg5, swig_voidp arg6);
extern swig_intgo _wrap_SeekLast_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_52 arg2, short arg3, short arg4, swig_voidp arg5);
extern swig_intgo _wrap_SetDateFormat_openace_035495a50e9dd2d9(swig_type_53 arg1);
extern swig_intgo _wrap_SetDefault_openace_035495a50e9dd2d9(swig_type_54 arg1);
extern swig_intgo _wrap_SetDouble_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_55 arg2, double arg3);
extern swig_intgo _wrap_SetEmpty_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_56 arg2);
extern swig_intgo _wrap_SetField_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_57 arg2, swig_type_58 arg3, swig_intgo arg4);
extern swig_intgo _wrap_SetFilter_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_59 arg2);
extern swig_intgo _wrap_SetJulian_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_60 arg2, swig_intgo arg3);
extern swig_intgo _wrap_SetLogical_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_61 arg2, short arg3);
extern swig_intgo _wrap_SetMilliseconds_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_62 arg2, swig_intgo arg3);
extern swig_intgo _wrap_SetRelKeyPos_openace_035495a50e9dd2d9(swig_intgo arg1, double arg2);
extern swig_intgo _wrap_SetSearchPath_openace_035495a50e9dd2d9(swig_type_63 arg1);
extern swig_intgo _wrap_SetString_openace_035495a50e9dd2d9(swig_intgo arg1, swig_type_64 arg2, swig_type_65 arg3, swig_intgo arg4);
extern swig_intgo _wrap_ShowDeleted_openace_035495a50e9dd2d9(short arg1);
extern swig_intgo _wrap_Skip_openace_035495a50e9dd2d9(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_UnlockRecord_openace_035495a50e9dd2d9(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_UnlockTable_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_WriteRecord_openace_035495a50e9dd2d9(swig_intgo arg1);
extern swig_intgo _wrap_ZapTable_openace_035495a50e9dd2d9(swig_intgo arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


func getSwigcptr(v interface { Swigcptr() uintptr }) uintptr {
	if v == nil {
		return 0
	}
	return v.Swigcptr()
}


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrHB_ACEDATA uintptr

func (p SwigcptrHB_ACEDATA) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrHB_ACEDATA) SwigIsHB_ACEDATA() {
}

func (arg1 SwigcptrHB_ACEDATA) SetUlLastError(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_HB_ACEDATA_ulLastError_set_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrHB_ACEDATA) GetUlLastError() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_HB_ACEDATA_ulLastError_get_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrHB_ACEDATA) SetBErrSeq(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_HB_ACEDATA_bErrSeq_set_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrHB_ACEDATA) GetBErrSeq() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_HB_ACEDATA_bErrSeq_get_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrHB_ACEDATA) SetBRTEOnce(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_HB_ACEDATA_bRTEOnce_set_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrHB_ACEDATA) GetBRTEOnce() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_HB_ACEDATA_bRTEOnce_get_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrHB_ACEDATA) SetSzRTE(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_HB_ACEDATA_szRTE_set_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0), *(*C.swig_type_1)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrHB_ACEDATA) GetSzRTE() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_HB_ACEDATA_szRTE_get_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrHB_ACEDATA) SetBXPPEatSlash(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_HB_ACEDATA_bXPPEatSlash_set_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrHB_ACEDATA) GetBXPPEatSlash() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_HB_ACEDATA_bXPPEatSlash_get_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrHB_ACEDATA) SetSzDbCdp(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_HB_ACEDATA_szDbCdp_set_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0), *(*C.swig_type_3)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrHB_ACEDATA) GetSzDbCdp() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_HB_ACEDATA_szDbCdp_get_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrHB_ACEDATA) SetSzVirtualPathCut(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_HB_ACEDATA_szVirtualPathCut_set_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0), *(*C.swig_type_5)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrHB_ACEDATA) GetSzVirtualPathCut() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_HB_ACEDATA_szVirtualPathCut_get_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrHB_ACEDATA) SetNVirtualPathLen(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_HB_ACEDATA_nVirtualPathLen_set_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrHB_ACEDATA) GetNVirtualPathLen() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_HB_ACEDATA_nVirtualPathLen_get_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrHB_ACEDATA) SetPCBTrace(arg2 uintptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_HB_ACEDATA_pCBTrace_set_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrHB_ACEDATA) GetPCBTrace() (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_HB_ACEDATA_pCBTrace_get_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrHB_ACEDATA) SetPCBOnRTE(arg2 uintptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_HB_ACEDATA_pCBOnRTE_set_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrHB_ACEDATA) GetPCBOnRTE() (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_HB_ACEDATA_pCBOnRTE_get_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewHB_ACEDATA() (_swig_ret HB_ACEDATA) {
	var swig_r HB_ACEDATA
	swig_r = (HB_ACEDATA)(SwigcptrHB_ACEDATA(C._wrap_new_HB_ACEDATA_openace_035495a50e9dd2d9()))
	return swig_r
}

func DeleteHB_ACEDATA(arg1 HB_ACEDATA) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_HB_ACEDATA_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0))
}

type HB_ACEDATA interface {
	Swigcptr() uintptr
	SwigIsHB_ACEDATA()
	SetUlLastError(arg2 uint)
	GetUlLastError() (_swig_ret uint)
	SetBErrSeq(arg2 int)
	GetBErrSeq() (_swig_ret int)
	SetBRTEOnce(arg2 int)
	GetBRTEOnce() (_swig_ret int)
	SetSzRTE(arg2 string)
	GetSzRTE() (_swig_ret string)
	SetBXPPEatSlash(arg2 int)
	GetBXPPEatSlash() (_swig_ret int)
	SetSzDbCdp(arg2 string)
	GetSzDbCdp() (_swig_ret string)
	SetSzVirtualPathCut(arg2 string)
	GetSzVirtualPathCut() (_swig_ret string)
	SetNVirtualPathLen(arg2 uint)
	GetNVirtualPathLen() (_swig_ret uint)
	SetPCBTrace(arg2 uintptr)
	GetPCBTrace() (_swig_ret uintptr)
	SetPCBOnRTE(arg2 uintptr)
	GetPCBOnRTE() (_swig_ret uintptr)
}

const ACE_FALSE int = 0
const ACE_TRUE int = 1
const ACE_DEFAULT int = 0
const ACE_REG_OWNER_LEN int = 36
const ACE_REVISION_LEN int = 16
const ACE_INST_DATE_LEN int = 16
const ACE_OEM_CHAR_NAME_LEN int = 16
const ACE_ANSI_CHAR_NAME_LEN int = 16
const ACE_SERIAL_NUM_LEN int = 16
const ACE_EXCLUSIVE int = 0x00000001
const ACE_READONLY int = 0x00000002
const ACE_SHARED int = 0x00000004
const ACE_CLIPPER_MEMOS int = 0x00000008
const ACE_TABLE_PERM_READ int = 0x00000010
const ACE_TABLE_PERM_UPDATE int = 0x00000020
const ACE_TABLE_PERM_INSERT int = 0x00000040
const ACE_TABLE_PERM_DELETE int = 0x00000080
const ACE_REINDEX_ON_COLLATION_MISMATCH int = 0x00000100
const ACE_IGNORE_COLLATION_MISMATCH int = 0x00000200
const ACE_FREE_TABLE int = 0x00001000
const ACE_TEMP_TABLE int = 0x00002000
const ACE_DICTIONARY_BOUND_TABLE int = 0x00004000
const ACE_CACHE_READS int = 0x20000000
const ACE_CACHE_WRITES int = 0x40000000
const ACE_ASCENDING int = 0x00000000
const ACE_UNIQUE int = 0x00000001
const ACE_COMPOUND int = 0x00000002
const ACE_CUSTOM int = 0x00000004
const ACE_DESCENDING int = 0x00000008
const ACE_USER_DEFINED int = 0x00000010
const ACE_RAWKEY int = 1
const ACE_STRINGKEY int = 2
const ACE_DOUBLEKEY int = 4
const ACE_WSTRINGKEY int = 8
const ACE_SOFTSEEK int = 0x0001
const ACE_HARDSEEK int = 0x0002
const ACE_SEEKGT int = 0x0004
const ACE_TOP int = 1
const ACE_BOTTOM int = 2
const ACE_RESPECTFILTERS int = 1
const ACE_IGNOREFILTERS int = 2
const ACE_RESPECTSCOPES int = 3
const ACE_DATABASE_TABLE int = 0
const ACE_NTX int = 1
const ACE_CDX int = 2
const ACE_ADT int = 3
const ACE_VFP int = 4
const ACE_TYPE_UNKNOWN int = 0
const ACE_LOGICAL int = 1
const ACE_NUMERIC int = 2
const ACE_DATE int = 3
const ACE_STRING int = 4
const ACE_MEMO int = 5
const ACE_BINARY int = 6
const ACE_IMAGE int = 7
const ACE_VARCHAR int = 8
const ACE_COMPACTDATE int = 9
const ACE_DOUBLE int = 10
const ACE_INTEGER int = 11
const ACE_SHORTINT int = 12
const ACE_TIME int = 13
const ACE_TIMESTAMP int = 14
const ACE_AUTOINC int = 15
const ACE_RAW int = 16
const ACE_CURDOUBLE int = 17
const ACE_MONEY int = 18
const ACE_LONGLONG int = 19
const ACE_CISTRING int = 20
const ACE_ROWVERSION int = 21
const ACE_MODTIME int = 22
const ACE_VARCHAR_FOX int = 23
const ACE_VARBINARY_FOX int = 24
const ACE_SYSTEM_FIELD int = 25
const ACE_NCHAR int = 26
const ACE_NVARCHAR int = 27
const ACE_NMEMO int = 28
const ACE_NONE int = 0x0000
const ACE_LTRIM int = 0x0001
const ACE_RTRIM int = 0x0002
const ACE_TRIM int = 0x0003
const ACE_GET_UTF8 int = 0x0004
const ACE_DONT_CHECK_CONV_ERR int = 0x0008
const ACE_GET_FORMAT_ANSI int = 0x0010
const ACE_GET_FORMAT_WEB int = 0x0030
const ACE_CONNECTION int = 1
const ACE_TABLE int = 2
const ACE_INDEX_ORDER int = 3
const ACE_STATEMENT int = 4
const ACE_CURSOR int = 5
const ACE_DATABASE_CONNECTION int = 6
const ACE_FTS_INDEX_ORDER int = 8
const ACE_MGMT_NT int = 2
const ACE_MGMT_LOCAL int = 3
const ACE_MGMT_LINUX int = 6
const ACE_MGMT_NT_64 int = 7
const ACE_MGMT_LINUX_64 int = 8
type SwigcptrACE_MGMT_INSTALL_INFO uintptr

func (p SwigcptrACE_MGMT_INSTALL_INFO) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrACE_MGMT_INSTALL_INFO) SwigIsACE_MGMT_INSTALL_INFO() {
}

func (arg1 SwigcptrACE_MGMT_INSTALL_INFO) SetUlUserOption(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ACE_MGMT_INSTALL_INFO_ulUserOption_set_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrACE_MGMT_INSTALL_INFO) GetUlUserOption() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_ACE_MGMT_INSTALL_INFO_ulUserOption_get_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrACE_MGMT_INSTALL_INFO) SetAucRegisteredOwner(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ACE_MGMT_INSTALL_INFO_aucRegisteredOwner_set_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0), *(*C.swig_type_7)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrACE_MGMT_INSTALL_INFO) GetAucRegisteredOwner() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_ACE_MGMT_INSTALL_INFO_aucRegisteredOwner_get_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrACE_MGMT_INSTALL_INFO) SetAucVersionStr(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ACE_MGMT_INSTALL_INFO_aucVersionStr_set_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0), *(*C.swig_type_9)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrACE_MGMT_INSTALL_INFO) GetAucVersionStr() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_ACE_MGMT_INSTALL_INFO_aucVersionStr_get_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrACE_MGMT_INSTALL_INFO) SetAucInstallDate(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ACE_MGMT_INSTALL_INFO_aucInstallDate_set_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0), *(*C.swig_type_11)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrACE_MGMT_INSTALL_INFO) GetAucInstallDate() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_ACE_MGMT_INSTALL_INFO_aucInstallDate_get_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrACE_MGMT_INSTALL_INFO) SetAucOemCharName(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ACE_MGMT_INSTALL_INFO_aucOemCharName_set_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0), *(*C.swig_type_13)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrACE_MGMT_INSTALL_INFO) GetAucOemCharName() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_ACE_MGMT_INSTALL_INFO_aucOemCharName_get_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrACE_MGMT_INSTALL_INFO) SetAucAnsiCharName(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ACE_MGMT_INSTALL_INFO_aucAnsiCharName_set_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0), *(*C.swig_type_15)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrACE_MGMT_INSTALL_INFO) GetAucAnsiCharName() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_ACE_MGMT_INSTALL_INFO_aucAnsiCharName_get_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrACE_MGMT_INSTALL_INFO) SetAucEvalExpireDate(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ACE_MGMT_INSTALL_INFO_aucEvalExpireDate_set_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0), *(*C.swig_type_17)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrACE_MGMT_INSTALL_INFO) GetAucEvalExpireDate() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_ACE_MGMT_INSTALL_INFO_aucEvalExpireDate_get_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrACE_MGMT_INSTALL_INFO) SetAucSerialNumber(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ACE_MGMT_INSTALL_INFO_aucSerialNumber_set_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0), *(*C.swig_type_19)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrACE_MGMT_INSTALL_INFO) GetAucSerialNumber() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_ACE_MGMT_INSTALL_INFO_aucSerialNumber_get_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrACE_MGMT_INSTALL_INFO) SetUlMaxStatefulUsers(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ACE_MGMT_INSTALL_INFO_ulMaxStatefulUsers_set_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrACE_MGMT_INSTALL_INFO) GetUlMaxStatefulUsers() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_ACE_MGMT_INSTALL_INFO_ulMaxStatefulUsers_get_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrACE_MGMT_INSTALL_INFO) SetUlMaxStatelessUsers(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ACE_MGMT_INSTALL_INFO_ulMaxStatelessUsers_set_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrACE_MGMT_INSTALL_INFO) GetUlMaxStatelessUsers() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_ACE_MGMT_INSTALL_INFO_ulMaxStatelessUsers_get_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewACE_MGMT_INSTALL_INFO() (_swig_ret ACE_MGMT_INSTALL_INFO) {
	var swig_r ACE_MGMT_INSTALL_INFO
	swig_r = (ACE_MGMT_INSTALL_INFO)(SwigcptrACE_MGMT_INSTALL_INFO(C._wrap_new_ACE_MGMT_INSTALL_INFO_openace_035495a50e9dd2d9()))
	return swig_r
}

func DeleteACE_MGMT_INSTALL_INFO(arg1 ACE_MGMT_INSTALL_INFO) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_ACE_MGMT_INSTALL_INFO_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0))
}

type ACE_MGMT_INSTALL_INFO interface {
	Swigcptr() uintptr
	SwigIsACE_MGMT_INSTALL_INFO()
	SetUlUserOption(arg2 uint)
	GetUlUserOption() (_swig_ret uint)
	SetAucRegisteredOwner(arg2 string)
	GetAucRegisteredOwner() (_swig_ret string)
	SetAucVersionStr(arg2 string)
	GetAucVersionStr() (_swig_ret string)
	SetAucInstallDate(arg2 string)
	GetAucInstallDate() (_swig_ret string)
	SetAucOemCharName(arg2 string)
	GetAucOemCharName() (_swig_ret string)
	SetAucAnsiCharName(arg2 string)
	GetAucAnsiCharName() (_swig_ret string)
	SetAucEvalExpireDate(arg2 string)
	GetAucEvalExpireDate() (_swig_ret string)
	SetAucSerialNumber(arg2 string)
	GetAucSerialNumber() (_swig_ret string)
	SetUlMaxStatefulUsers(arg2 uint)
	GetUlMaxStatefulUsers() (_swig_ret uint)
	SetUlMaxStatelessUsers(arg2 uint)
	GetUlMaxStatelessUsers() (_swig_ret uint)
}

func SysSetTable(arg1 *uint, arg2 int, arg3 HB_ACEDATA, arg4 string) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := getSwigcptr(arg3)
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_SysSetTable_openace_035495a50e9dd2d9(C.swig_voidp(_swig_i_0), C.swig_intgo(_swig_i_1), C.uintptr_t(_swig_i_2), *(*C.swig_type_21)(unsafe.Pointer(&_swig_i_3))))
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
	return swig_r
}

func SetCallbackOnRTE(arg1 uintptr) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_SetCallbackOnRTE_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SetCallbackTrace(arg1 uintptr) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_SetCallbackTrace_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func AddCustomKey(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_AddCustomKey_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func AppendRecord(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_AppendRecord_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func ApplicationExit() (_swig_ret uint) {
	var swig_r uint
	swig_r = (uint)(C._wrap_ApplicationExit_openace_035495a50e9dd2d9())
	return swig_r
}

func AtBOF(arg1 uint, arg2 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_AtBOF_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func AtEOF(arg1 uint, arg2 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_AtEOF_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func CacheRecords(arg1 uint, arg2 uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_CacheRecords_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.short(_swig_i_1)))
	return swig_r
}

func BeginTransaction(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_BeginTransaction_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func ClearFilter(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_ClearFilter_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func ClearProgressCallback() (_swig_ret uint) {
	var swig_r uint
	swig_r = (uint)(C._wrap_ClearProgressCallback_openace_035495a50e9dd2d9())
	return swig_r
}

func ClearRelation(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_ClearRelation_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func ClearScope(arg1 uint, arg2 uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_ClearScope_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.short(_swig_i_1)))
	return swig_r
}

func CloseAllIndexes(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_CloseAllIndexes_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func CloseIndex(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_CloseIndex_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func CloseTable(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_CloseTable_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func CommitTransaction(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_CommitTransaction_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Connect(arg1 string, arg2 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_Connect_openace_035495a50e9dd2d9(*(*C.swig_type_22)(unsafe.Pointer(&_swig_i_0)), C.swig_voidp(_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func CopyTableContents(arg1 uint, arg2 uint, arg3 uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_CopyTableContents_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.short(_swig_i_2)))
	return swig_r
}

func CreateIndex(arg1 uint, arg2 string, arg3 string, arg4 string, arg5 string, arg6 string, arg7 uint, arg8 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	swig_r = (uint)(C._wrap_CreateIndex_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_23)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_24)(unsafe.Pointer(&_swig_i_2)), *(*C.swig_type_25)(unsafe.Pointer(&_swig_i_3)), *(*C.swig_type_26)(unsafe.Pointer(&_swig_i_4)), *(*C.swig_type_27)(unsafe.Pointer(&_swig_i_5)), C.swig_intgo(_swig_i_6), C.swig_voidp(_swig_i_7)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg5
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg6
	}
	return swig_r
}

func CreateTable(arg1 uint, arg2 string, arg3 string, arg4 uint16, arg5 uint16, arg6 uint16, arg7 uint16, arg8 uint16, arg9 string, arg10 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	_swig_i_8 := arg9
	_swig_i_9 := arg10
	swig_r = (uint)(C._wrap_CreateTable_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_28)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_29)(unsafe.Pointer(&_swig_i_2)), C.short(_swig_i_3), C.short(_swig_i_4), C.short(_swig_i_5), C.short(_swig_i_6), C.short(_swig_i_7), *(*C.swig_type_30)(unsafe.Pointer(&_swig_i_8)), C.swig_voidp(_swig_i_9)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg9
	}
	return swig_r
}

func DeleteCustomKey(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_DeleteCustomKey_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func DeleteIndex(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_DeleteIndex_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func DeleteRecord(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_DeleteRecord_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Disconnect(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_Disconnect_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func ExtractKey(arg1 uint, arg2 uintptr, arg3 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_ExtractKey_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func GetAllIndexes(arg1 uint, arg2 *uint, arg3 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetAllIndexes_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func GetAllLocks(arg1 uint, arg2 *uint, arg3 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetAllLocks_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func GetBinary(arg1 uint, arg2 string, arg3 uint, arg4 uintptr, arg5 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (uint)(C._wrap_GetBinary_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_31)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2), C.uintptr_t(_swig_i_3), C.swig_voidp(_swig_i_4)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func GetBinaryLength(arg1 uint, arg2 string, arg3 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetBinaryLength_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_32)(unsafe.Pointer(&_swig_i_1)), C.swig_voidp(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func GetDateFormat(arg1 uintptr, arg2 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_GetDateFormat_openace_035495a50e9dd2d9(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func GetDouble(arg1 uint, arg2 string, arg3 *float64) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetDouble_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_33)(unsafe.Pointer(&_swig_i_1)), C.swig_voidp(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func GetErrorString(arg1 uint, arg2 uintptr, arg3 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetErrorString_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func GetField(arg1 uint, arg2 string, arg3 uintptr, arg4 *uint, arg5 uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (uint)(C._wrap_GetField_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_34)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2), C.swig_voidp(_swig_i_3), C.short(_swig_i_4)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func GetFieldDecimals(arg1 uint, arg2 string, arg3 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetFieldDecimals_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_35)(unsafe.Pointer(&_swig_i_1)), C.swig_voidp(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func GetFieldLength(arg1 uint, arg2 string, arg3 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetFieldLength_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_36)(unsafe.Pointer(&_swig_i_1)), C.swig_voidp(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func GetFieldName(arg1 uint, arg2 uint16, arg3 uintptr, arg4 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_GetFieldName_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func GetFieldType(arg1 uint, arg2 string, arg3 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetFieldType_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_37)(unsafe.Pointer(&_swig_i_1)), C.swig_voidp(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func GetHandleType(arg1 uint, arg2 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_GetHandleType_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func GetIndexCondition(arg1 uint, arg2 uintptr, arg3 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetIndexCondition_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func GetIndexExpr(arg1 uint, arg2 uintptr, arg3 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetIndexExpr_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func GetIndexFilename(arg1 uint, arg2 uint16, arg3 uintptr, arg4 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_GetIndexFilename_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func GetIndexName(arg1 uint, arg2 uintptr, arg3 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetIndexName_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func GetIndexHandle(arg1 uint, arg2 string, arg3 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetIndexHandle_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_38)(unsafe.Pointer(&_swig_i_1)), C.swig_voidp(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func GetIndexHandleByOrder(arg1 uint, arg2 uint16, arg3 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetIndexHandleByOrder_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func GetJulian(arg1 uint, arg2 string, arg3 *int) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetJulian_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_39)(unsafe.Pointer(&_swig_i_1)), C.swig_voidp(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func GetKeyCount(arg1 uint, arg2 uint16, arg3 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetKeyCount_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func GetKeyLength(arg1 uint, arg2 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_GetKeyLength_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func GetKeyNum(arg1 uint, arg2 uint16, arg3 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetKeyNum_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func GetKeyType(arg1 uint, arg2 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_GetKeyType_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func GetLastError(arg1 *uint, arg2 uintptr, arg3 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetLastError_openace_035495a50e9dd2d9(C.swig_voidp(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func GetLastTableUpdate(arg1 uint, arg2 uintptr, arg3 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetLastTableUpdate_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func GetLogical(arg1 uint, arg2 string, arg3 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetLogical_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_40)(unsafe.Pointer(&_swig_i_1)), C.swig_voidp(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func GetMemoLength(arg1 uint, arg2 string, arg3 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetMemoLength_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_41)(unsafe.Pointer(&_swig_i_1)), C.swig_voidp(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func GetMilliseconds(arg1 uint, arg2 string, arg3 *int) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetMilliseconds_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_42)(unsafe.Pointer(&_swig_i_1)), C.swig_voidp(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func GetNumFields(arg1 uint, arg2 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_GetNumFields_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func GetNumIndexes(arg1 uint, arg2 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_GetNumIndexes_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func GetNumLocks(arg1 uint, arg2 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_GetNumLocks_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func GetRecordCount(arg1 uint, arg2 uint16, arg3 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetRecordCount_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func GetRecordNum(arg1 uint, arg2 uint16, arg3 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetRecordNum_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func GetRecordLength(arg1 uint, arg2 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_GetRecordLength_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func GetRelKeyPos(arg1 uint, arg2 *float64) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_GetRelKeyPos_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func GetServerName(arg1 uint, arg2 uintptr, arg3 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetServerName_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func GetString(arg1 uint, arg2 string, arg3 uintptr, arg4 *uint, arg5 uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (uint)(C._wrap_GetString_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_43)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2), C.swig_voidp(_swig_i_3), C.short(_swig_i_4)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func GetTableAlias(arg1 uint, arg2 uintptr, arg3 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_GetTableAlias_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func GetTableFilename(arg1 uint, arg2 uint16, arg3 uintptr, arg4 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_GetTableFilename_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func GetTableType(arg1 uint, arg2 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_GetTableType_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func GotoBottom(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_GotoBottom_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func GotoRecord(arg1 uint, arg2 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_GotoRecord_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func GotoTop(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_GotoTop_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func IsEmpty(arg1 uint, arg2 string, arg3 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_IsEmpty_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_44)(unsafe.Pointer(&_swig_i_1)), C.swig_voidp(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func IsIndexDescending(arg1 uint, arg2 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_IsIndexDescending_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func IsIndexUnique(arg1 uint, arg2 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_IsIndexUnique_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func IsRecordDeleted(arg1 uint, arg2 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_IsRecordDeleted_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func LockRecord(arg1 uint, arg2 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_LockRecord_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func LockTable(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_LockTable_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func MgConnect(arg1 string, arg2 string, arg3 string, arg4 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_MgConnect_openace_035495a50e9dd2d9(*(*C.swig_type_45)(unsafe.Pointer(&_swig_i_0)), *(*C.swig_type_46)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_47)(unsafe.Pointer(&_swig_i_2)), C.swig_voidp(_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func MgDisconnect(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_MgDisconnect_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func MgGetInstallInfo(arg1 uint, arg2 ACE_MGMT_INSTALL_INFO, arg3 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_MgGetInstallInfo_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func MgGetServerType(arg1 uint, arg2 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_MgGetServerType_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func NullTerminateStrings(arg1 uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_NullTerminateStrings_openace_035495a50e9dd2d9(C.short(_swig_i_0)))
	return swig_r
}

func OpenIndex(arg1 uint, arg2 string, arg3 *uint, arg4 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_OpenIndex_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_48)(unsafe.Pointer(&_swig_i_1)), C.swig_voidp(_swig_i_2), C.swig_voidp(_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func OpenTable(arg1 uint, arg2 string, arg3 string, arg4 uint16, arg5 uint16, arg6 uint16, arg7 uint16, arg8 uint, arg9 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	_swig_i_8 := arg9
	swig_r = (uint)(C._wrap_OpenTable_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_49)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_50)(unsafe.Pointer(&_swig_i_2)), C.short(_swig_i_3), C.short(_swig_i_4), C.short(_swig_i_5), C.short(_swig_i_6), C.swig_intgo(_swig_i_7), C.swig_voidp(_swig_i_8)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func PackTable(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_PackTable_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func RecallRecord(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_RecallRecord_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func RefreshRecord(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_RefreshRecord_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Reindex(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_Reindex_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func RollbackTransaction(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_RollbackTransaction_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Seek(arg1 uint, arg2 string, arg3 uint16, arg4 uint16, arg5 uint16, arg6 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (uint)(C._wrap_Seek_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_51)(unsafe.Pointer(&_swig_i_1)), C.short(_swig_i_2), C.short(_swig_i_3), C.short(_swig_i_4), C.swig_voidp(_swig_i_5)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func SeekLast(arg1 uint, arg2 string, arg3 uint16, arg4 uint16, arg5 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (uint)(C._wrap_SeekLast_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_52)(unsafe.Pointer(&_swig_i_1)), C.short(_swig_i_2), C.short(_swig_i_3), C.swig_voidp(_swig_i_4)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func SetDateFormat(arg1 string) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_SetDateFormat_openace_035495a50e9dd2d9(*(*C.swig_type_53)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func SetDefault(arg1 string) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_SetDefault_openace_035495a50e9dd2d9(*(*C.swig_type_54)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func SetDouble(arg1 uint, arg2 string, arg3 float64) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_SetDouble_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_55)(unsafe.Pointer(&_swig_i_1)), C.double(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func SetEmpty(arg1 uint, arg2 string) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_SetEmpty_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_56)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func SetField(arg1 uint, arg2 string, arg3 string, arg4 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_SetField_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_57)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_58)(unsafe.Pointer(&_swig_i_2)), C.swig_intgo(_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func SetFilter(arg1 uint, arg2 string) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_SetFilter_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_59)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func SetJulian(arg1 uint, arg2 string, arg3 int) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_SetJulian_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_60)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func SetLogical(arg1 uint, arg2 string, arg3 uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_SetLogical_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_61)(unsafe.Pointer(&_swig_i_1)), C.short(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func SetMilliseconds(arg1 uint, arg2 string, arg3 int) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_SetMilliseconds_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_62)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func SetRelKeyPos(arg1 uint, arg2 float64) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_SetRelKeyPos_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.double(_swig_i_1)))
	return swig_r
}

func SetSearchPath(arg1 string) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_SetSearchPath_openace_035495a50e9dd2d9(*(*C.swig_type_63)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func SetString(arg1 uint, arg2 string, arg3 string, arg4 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_SetString_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), *(*C.swig_type_64)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_65)(unsafe.Pointer(&_swig_i_2)), C.swig_intgo(_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func ShowDeleted(arg1 uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_ShowDeleted_openace_035495a50e9dd2d9(C.short(_swig_i_0)))
	return swig_r
}

func Skip(arg1 uint, arg2 int) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_Skip_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func UnlockRecord(arg1 uint, arg2 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_UnlockRecord_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func UnlockTable(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_UnlockTable_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func WriteRecord(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_WriteRecord_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func ZapTable(arg1 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_ZapTable_openace_035495a50e9dd2d9(C.swig_intgo(_swig_i_0)))
	return swig_r
}


