/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: openace.i */



#define SWIG_VERSION 0x040101
#define SWIGGO
#define SWIGMODULE openace
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef ptrdiff_t intgo;
typedef size_t uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;



static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include <hbdefs.h>
#include <hbapi.h>
#include <hbapirdd.h>

#include "include/openace.h"


#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_openace_035495a50e9dd2d9(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_HB_ACEDATA_ulLastError_set_openace_035495a50e9dd2d9(HB_ACEDATA *_swig_go_0, intgo _swig_go_1) {
  HB_ACEDATA *arg1 = (HB_ACEDATA *) 0 ;
  HB_U32 arg2 ;
  
  arg1 = *(HB_ACEDATA **)&_swig_go_0; 
  arg2 = (HB_U32)_swig_go_1; 
  
  if (arg1) (arg1)->ulLastError = arg2;
  
}


intgo _wrap_HB_ACEDATA_ulLastError_get_openace_035495a50e9dd2d9(HB_ACEDATA *_swig_go_0) {
  HB_ACEDATA *arg1 = (HB_ACEDATA *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = *(HB_ACEDATA **)&_swig_go_0; 
  
  result = (HB_U32) ((arg1)->ulLastError);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_HB_ACEDATA_bErrSeq_set_openace_035495a50e9dd2d9(HB_ACEDATA *_swig_go_0, intgo _swig_go_1) {
  HB_ACEDATA *arg1 = (HB_ACEDATA *) 0 ;
  HB_BOOL arg2 ;
  
  arg1 = *(HB_ACEDATA **)&_swig_go_0; 
  arg2 = (HB_BOOL)_swig_go_1; 
  
  if (arg1) (arg1)->bErrSeq = arg2;
  
}


intgo _wrap_HB_ACEDATA_bErrSeq_get_openace_035495a50e9dd2d9(HB_ACEDATA *_swig_go_0) {
  HB_ACEDATA *arg1 = (HB_ACEDATA *) 0 ;
  HB_BOOL result;
  intgo _swig_go_result;
  
  arg1 = *(HB_ACEDATA **)&_swig_go_0; 
  
  result = (HB_BOOL) ((arg1)->bErrSeq);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_HB_ACEDATA_bRTEOnce_set_openace_035495a50e9dd2d9(HB_ACEDATA *_swig_go_0, intgo _swig_go_1) {
  HB_ACEDATA *arg1 = (HB_ACEDATA *) 0 ;
  HB_BOOL arg2 ;
  
  arg1 = *(HB_ACEDATA **)&_swig_go_0; 
  arg2 = (HB_BOOL)_swig_go_1; 
  
  if (arg1) (arg1)->bRTEOnce = arg2;
  
}


intgo _wrap_HB_ACEDATA_bRTEOnce_get_openace_035495a50e9dd2d9(HB_ACEDATA *_swig_go_0) {
  HB_ACEDATA *arg1 = (HB_ACEDATA *) 0 ;
  HB_BOOL result;
  intgo _swig_go_result;
  
  arg1 = *(HB_ACEDATA **)&_swig_go_0; 
  
  result = (HB_BOOL) ((arg1)->bRTEOnce);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_HB_ACEDATA_szRTE_set_openace_035495a50e9dd2d9(HB_ACEDATA *_swig_go_0, _gostring_ _swig_go_1) {
  HB_ACEDATA *arg1 = (HB_ACEDATA *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = *(HB_ACEDATA **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    free(arg1->szRTE);
    if (arg2) {
      arg1->szRTE = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->szRTE, (const char *)arg2);
    } else {
      arg1->szRTE = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_HB_ACEDATA_szRTE_get_openace_035495a50e9dd2d9(HB_ACEDATA *_swig_go_0) {
  HB_ACEDATA *arg1 = (HB_ACEDATA *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(HB_ACEDATA **)&_swig_go_0; 
  
  result = (char *) ((arg1)->szRTE);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_HB_ACEDATA_bXPPEatSlash_set_openace_035495a50e9dd2d9(HB_ACEDATA *_swig_go_0, intgo _swig_go_1) {
  HB_ACEDATA *arg1 = (HB_ACEDATA *) 0 ;
  HB_BOOL arg2 ;
  
  arg1 = *(HB_ACEDATA **)&_swig_go_0; 
  arg2 = (HB_BOOL)_swig_go_1; 
  
  if (arg1) (arg1)->bXPPEatSlash = arg2;
  
}


intgo _wrap_HB_ACEDATA_bXPPEatSlash_get_openace_035495a50e9dd2d9(HB_ACEDATA *_swig_go_0) {
  HB_ACEDATA *arg1 = (HB_ACEDATA *) 0 ;
  HB_BOOL result;
  intgo _swig_go_result;
  
  arg1 = *(HB_ACEDATA **)&_swig_go_0; 
  
  result = (HB_BOOL) ((arg1)->bXPPEatSlash);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_HB_ACEDATA_szDbCdp_set_openace_035495a50e9dd2d9(HB_ACEDATA *_swig_go_0, _gostring_ _swig_go_1) {
  HB_ACEDATA *arg1 = (HB_ACEDATA *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = *(HB_ACEDATA **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    free(arg1->szDbCdp);
    if (arg2) {
      arg1->szDbCdp = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->szDbCdp, (const char *)arg2);
    } else {
      arg1->szDbCdp = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_HB_ACEDATA_szDbCdp_get_openace_035495a50e9dd2d9(HB_ACEDATA *_swig_go_0) {
  HB_ACEDATA *arg1 = (HB_ACEDATA *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(HB_ACEDATA **)&_swig_go_0; 
  
  result = (char *) ((arg1)->szDbCdp);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_HB_ACEDATA_szVirtualPathCut_set_openace_035495a50e9dd2d9(HB_ACEDATA *_swig_go_0, _gostring_ _swig_go_1) {
  HB_ACEDATA *arg1 = (HB_ACEDATA *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = *(HB_ACEDATA **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    free(arg1->szVirtualPathCut);
    if (arg2) {
      arg1->szVirtualPathCut = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->szVirtualPathCut, (const char *)arg2);
    } else {
      arg1->szVirtualPathCut = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_HB_ACEDATA_szVirtualPathCut_get_openace_035495a50e9dd2d9(HB_ACEDATA *_swig_go_0) {
  HB_ACEDATA *arg1 = (HB_ACEDATA *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(HB_ACEDATA **)&_swig_go_0; 
  
  result = (char *) ((arg1)->szVirtualPathCut);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_HB_ACEDATA_nVirtualPathLen_set_openace_035495a50e9dd2d9(HB_ACEDATA *_swig_go_0, intgo _swig_go_1) {
  HB_ACEDATA *arg1 = (HB_ACEDATA *) 0 ;
  HB_U32 arg2 ;
  
  arg1 = *(HB_ACEDATA **)&_swig_go_0; 
  arg2 = (HB_U32)_swig_go_1; 
  
  if (arg1) (arg1)->nVirtualPathLen = arg2;
  
}


intgo _wrap_HB_ACEDATA_nVirtualPathLen_get_openace_035495a50e9dd2d9(HB_ACEDATA *_swig_go_0) {
  HB_ACEDATA *arg1 = (HB_ACEDATA *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = *(HB_ACEDATA **)&_swig_go_0; 
  
  result = (HB_U32) ((arg1)->nVirtualPathLen);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_HB_ACEDATA_pCBTrace_set_openace_035495a50e9dd2d9(HB_ACEDATA *_swig_go_0, void *_swig_go_1) {
  HB_ACEDATA *arg1 = (HB_ACEDATA *) 0 ;
  void *arg2 = (void *) 0 ;
  
  arg1 = *(HB_ACEDATA **)&_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  
  if (arg1) (arg1)->pCBTrace = arg2;
  
}


void *_wrap_HB_ACEDATA_pCBTrace_get_openace_035495a50e9dd2d9(HB_ACEDATA *_swig_go_0) {
  HB_ACEDATA *arg1 = (HB_ACEDATA *) 0 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(HB_ACEDATA **)&_swig_go_0; 
  
  result = (void *) ((arg1)->pCBTrace);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_HB_ACEDATA_pCBOnRTE_set_openace_035495a50e9dd2d9(HB_ACEDATA *_swig_go_0, void *_swig_go_1) {
  HB_ACEDATA *arg1 = (HB_ACEDATA *) 0 ;
  void *arg2 = (void *) 0 ;
  
  arg1 = *(HB_ACEDATA **)&_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  
  if (arg1) (arg1)->pCBOnRTE = arg2;
  
}


void *_wrap_HB_ACEDATA_pCBOnRTE_get_openace_035495a50e9dd2d9(HB_ACEDATA *_swig_go_0) {
  HB_ACEDATA *arg1 = (HB_ACEDATA *) 0 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(HB_ACEDATA **)&_swig_go_0; 
  
  result = (void *) ((arg1)->pCBOnRTE);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


HB_ACEDATA *_wrap_new_HB_ACEDATA_openace_035495a50e9dd2d9() {
  HB_ACEDATA *result = 0 ;
  HB_ACEDATA *_swig_go_result;
  
  
  result = (HB_ACEDATA *)calloc(1, sizeof(HB_ACEDATA));
  *(HB_ACEDATA **)&_swig_go_result = (HB_ACEDATA *)result; 
  return _swig_go_result;
}


void _wrap_delete_HB_ACEDATA_openace_035495a50e9dd2d9(HB_ACEDATA *_swig_go_0) {
  HB_ACEDATA *arg1 = (HB_ACEDATA *) 0 ;
  
  arg1 = *(HB_ACEDATA **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


void _wrap_ACE_MGMT_INSTALL_INFO_ulUserOption_set_openace_035495a50e9dd2d9(ACE_MGMT_INSTALL_INFO *_swig_go_0, intgo _swig_go_1) {
  ACE_MGMT_INSTALL_INFO *arg1 = (ACE_MGMT_INSTALL_INFO *) 0 ;
  HB_U32 arg2 ;
  
  arg1 = *(ACE_MGMT_INSTALL_INFO **)&_swig_go_0; 
  arg2 = (HB_U32)_swig_go_1; 
  
  if (arg1) (arg1)->ulUserOption = arg2;
  
}


intgo _wrap_ACE_MGMT_INSTALL_INFO_ulUserOption_get_openace_035495a50e9dd2d9(ACE_MGMT_INSTALL_INFO *_swig_go_0) {
  ACE_MGMT_INSTALL_INFO *arg1 = (ACE_MGMT_INSTALL_INFO *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = *(ACE_MGMT_INSTALL_INFO **)&_swig_go_0; 
  
  result = (HB_U32) ((arg1)->ulUserOption);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_ACE_MGMT_INSTALL_INFO_aucRegisteredOwner_set_openace_035495a50e9dd2d9(ACE_MGMT_INSTALL_INFO *_swig_go_0, _gostring_ _swig_go_1) {
  ACE_MGMT_INSTALL_INFO *arg1 = (ACE_MGMT_INSTALL_INFO *) 0 ;
  HB_UCHAR *arg2 ;
  
  arg1 = *(ACE_MGMT_INSTALL_INFO **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    if(arg2) {
      strncpy((char*)arg1->aucRegisteredOwner, (const char *)arg2, 36-1);
      arg1->aucRegisteredOwner[36-1] = 0;
    } else {
      arg1->aucRegisteredOwner[0] = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_ACE_MGMT_INSTALL_INFO_aucRegisteredOwner_get_openace_035495a50e9dd2d9(ACE_MGMT_INSTALL_INFO *_swig_go_0) {
  ACE_MGMT_INSTALL_INFO *arg1 = (ACE_MGMT_INSTALL_INFO *) 0 ;
  HB_UCHAR *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(ACE_MGMT_INSTALL_INFO **)&_swig_go_0; 
  
  result = (HB_UCHAR *)(HB_UCHAR *) ((arg1)->aucRegisteredOwner);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_ACE_MGMT_INSTALL_INFO_aucVersionStr_set_openace_035495a50e9dd2d9(ACE_MGMT_INSTALL_INFO *_swig_go_0, _gostring_ _swig_go_1) {
  ACE_MGMT_INSTALL_INFO *arg1 = (ACE_MGMT_INSTALL_INFO *) 0 ;
  HB_UCHAR *arg2 ;
  
  arg1 = *(ACE_MGMT_INSTALL_INFO **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    if(arg2) {
      strncpy((char*)arg1->aucVersionStr, (const char *)arg2, 16-1);
      arg1->aucVersionStr[16-1] = 0;
    } else {
      arg1->aucVersionStr[0] = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_ACE_MGMT_INSTALL_INFO_aucVersionStr_get_openace_035495a50e9dd2d9(ACE_MGMT_INSTALL_INFO *_swig_go_0) {
  ACE_MGMT_INSTALL_INFO *arg1 = (ACE_MGMT_INSTALL_INFO *) 0 ;
  HB_UCHAR *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(ACE_MGMT_INSTALL_INFO **)&_swig_go_0; 
  
  result = (HB_UCHAR *)(HB_UCHAR *) ((arg1)->aucVersionStr);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_ACE_MGMT_INSTALL_INFO_aucInstallDate_set_openace_035495a50e9dd2d9(ACE_MGMT_INSTALL_INFO *_swig_go_0, _gostring_ _swig_go_1) {
  ACE_MGMT_INSTALL_INFO *arg1 = (ACE_MGMT_INSTALL_INFO *) 0 ;
  HB_UCHAR *arg2 ;
  
  arg1 = *(ACE_MGMT_INSTALL_INFO **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    if(arg2) {
      strncpy((char*)arg1->aucInstallDate, (const char *)arg2, 16-1);
      arg1->aucInstallDate[16-1] = 0;
    } else {
      arg1->aucInstallDate[0] = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_ACE_MGMT_INSTALL_INFO_aucInstallDate_get_openace_035495a50e9dd2d9(ACE_MGMT_INSTALL_INFO *_swig_go_0) {
  ACE_MGMT_INSTALL_INFO *arg1 = (ACE_MGMT_INSTALL_INFO *) 0 ;
  HB_UCHAR *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(ACE_MGMT_INSTALL_INFO **)&_swig_go_0; 
  
  result = (HB_UCHAR *)(HB_UCHAR *) ((arg1)->aucInstallDate);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_ACE_MGMT_INSTALL_INFO_aucOemCharName_set_openace_035495a50e9dd2d9(ACE_MGMT_INSTALL_INFO *_swig_go_0, _gostring_ _swig_go_1) {
  ACE_MGMT_INSTALL_INFO *arg1 = (ACE_MGMT_INSTALL_INFO *) 0 ;
  HB_UCHAR *arg2 ;
  
  arg1 = *(ACE_MGMT_INSTALL_INFO **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    if(arg2) {
      strncpy((char*)arg1->aucOemCharName, (const char *)arg2, 16-1);
      arg1->aucOemCharName[16-1] = 0;
    } else {
      arg1->aucOemCharName[0] = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_ACE_MGMT_INSTALL_INFO_aucOemCharName_get_openace_035495a50e9dd2d9(ACE_MGMT_INSTALL_INFO *_swig_go_0) {
  ACE_MGMT_INSTALL_INFO *arg1 = (ACE_MGMT_INSTALL_INFO *) 0 ;
  HB_UCHAR *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(ACE_MGMT_INSTALL_INFO **)&_swig_go_0; 
  
  result = (HB_UCHAR *)(HB_UCHAR *) ((arg1)->aucOemCharName);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_ACE_MGMT_INSTALL_INFO_aucAnsiCharName_set_openace_035495a50e9dd2d9(ACE_MGMT_INSTALL_INFO *_swig_go_0, _gostring_ _swig_go_1) {
  ACE_MGMT_INSTALL_INFO *arg1 = (ACE_MGMT_INSTALL_INFO *) 0 ;
  HB_UCHAR *arg2 ;
  
  arg1 = *(ACE_MGMT_INSTALL_INFO **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    if(arg2) {
      strncpy((char*)arg1->aucAnsiCharName, (const char *)arg2, 16-1);
      arg1->aucAnsiCharName[16-1] = 0;
    } else {
      arg1->aucAnsiCharName[0] = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_ACE_MGMT_INSTALL_INFO_aucAnsiCharName_get_openace_035495a50e9dd2d9(ACE_MGMT_INSTALL_INFO *_swig_go_0) {
  ACE_MGMT_INSTALL_INFO *arg1 = (ACE_MGMT_INSTALL_INFO *) 0 ;
  HB_UCHAR *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(ACE_MGMT_INSTALL_INFO **)&_swig_go_0; 
  
  result = (HB_UCHAR *)(HB_UCHAR *) ((arg1)->aucAnsiCharName);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_ACE_MGMT_INSTALL_INFO_aucEvalExpireDate_set_openace_035495a50e9dd2d9(ACE_MGMT_INSTALL_INFO *_swig_go_0, _gostring_ _swig_go_1) {
  ACE_MGMT_INSTALL_INFO *arg1 = (ACE_MGMT_INSTALL_INFO *) 0 ;
  HB_UCHAR *arg2 ;
  
  arg1 = *(ACE_MGMT_INSTALL_INFO **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    if(arg2) {
      strncpy((char*)arg1->aucEvalExpireDate, (const char *)arg2, 16-1);
      arg1->aucEvalExpireDate[16-1] = 0;
    } else {
      arg1->aucEvalExpireDate[0] = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_ACE_MGMT_INSTALL_INFO_aucEvalExpireDate_get_openace_035495a50e9dd2d9(ACE_MGMT_INSTALL_INFO *_swig_go_0) {
  ACE_MGMT_INSTALL_INFO *arg1 = (ACE_MGMT_INSTALL_INFO *) 0 ;
  HB_UCHAR *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(ACE_MGMT_INSTALL_INFO **)&_swig_go_0; 
  
  result = (HB_UCHAR *)(HB_UCHAR *) ((arg1)->aucEvalExpireDate);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_ACE_MGMT_INSTALL_INFO_aucSerialNumber_set_openace_035495a50e9dd2d9(ACE_MGMT_INSTALL_INFO *_swig_go_0, _gostring_ _swig_go_1) {
  ACE_MGMT_INSTALL_INFO *arg1 = (ACE_MGMT_INSTALL_INFO *) 0 ;
  HB_UCHAR *arg2 ;
  
  arg1 = *(ACE_MGMT_INSTALL_INFO **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    if(arg2) {
      strncpy((char*)arg1->aucSerialNumber, (const char *)arg2, 16-1);
      arg1->aucSerialNumber[16-1] = 0;
    } else {
      arg1->aucSerialNumber[0] = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_ACE_MGMT_INSTALL_INFO_aucSerialNumber_get_openace_035495a50e9dd2d9(ACE_MGMT_INSTALL_INFO *_swig_go_0) {
  ACE_MGMT_INSTALL_INFO *arg1 = (ACE_MGMT_INSTALL_INFO *) 0 ;
  HB_UCHAR *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(ACE_MGMT_INSTALL_INFO **)&_swig_go_0; 
  
  result = (HB_UCHAR *)(HB_UCHAR *) ((arg1)->aucSerialNumber);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_ACE_MGMT_INSTALL_INFO_ulMaxStatefulUsers_set_openace_035495a50e9dd2d9(ACE_MGMT_INSTALL_INFO *_swig_go_0, intgo _swig_go_1) {
  ACE_MGMT_INSTALL_INFO *arg1 = (ACE_MGMT_INSTALL_INFO *) 0 ;
  HB_U32 arg2 ;
  
  arg1 = *(ACE_MGMT_INSTALL_INFO **)&_swig_go_0; 
  arg2 = (HB_U32)_swig_go_1; 
  
  if (arg1) (arg1)->ulMaxStatefulUsers = arg2;
  
}


intgo _wrap_ACE_MGMT_INSTALL_INFO_ulMaxStatefulUsers_get_openace_035495a50e9dd2d9(ACE_MGMT_INSTALL_INFO *_swig_go_0) {
  ACE_MGMT_INSTALL_INFO *arg1 = (ACE_MGMT_INSTALL_INFO *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = *(ACE_MGMT_INSTALL_INFO **)&_swig_go_0; 
  
  result = (HB_U32) ((arg1)->ulMaxStatefulUsers);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_ACE_MGMT_INSTALL_INFO_ulMaxStatelessUsers_set_openace_035495a50e9dd2d9(ACE_MGMT_INSTALL_INFO *_swig_go_0, intgo _swig_go_1) {
  ACE_MGMT_INSTALL_INFO *arg1 = (ACE_MGMT_INSTALL_INFO *) 0 ;
  HB_U32 arg2 ;
  
  arg1 = *(ACE_MGMT_INSTALL_INFO **)&_swig_go_0; 
  arg2 = (HB_U32)_swig_go_1; 
  
  if (arg1) (arg1)->ulMaxStatelessUsers = arg2;
  
}


intgo _wrap_ACE_MGMT_INSTALL_INFO_ulMaxStatelessUsers_get_openace_035495a50e9dd2d9(ACE_MGMT_INSTALL_INFO *_swig_go_0) {
  ACE_MGMT_INSTALL_INFO *arg1 = (ACE_MGMT_INSTALL_INFO *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = *(ACE_MGMT_INSTALL_INFO **)&_swig_go_0; 
  
  result = (HB_U32) ((arg1)->ulMaxStatelessUsers);
  _swig_go_result = result; 
  return _swig_go_result;
}


ACE_MGMT_INSTALL_INFO *_wrap_new_ACE_MGMT_INSTALL_INFO_openace_035495a50e9dd2d9() {
  ACE_MGMT_INSTALL_INFO *result = 0 ;
  ACE_MGMT_INSTALL_INFO *_swig_go_result;
  
  
  result = (ACE_MGMT_INSTALL_INFO *)calloc(1, sizeof(ACE_MGMT_INSTALL_INFO));
  *(ACE_MGMT_INSTALL_INFO **)&_swig_go_result = (ACE_MGMT_INSTALL_INFO *)result; 
  return _swig_go_result;
}


void _wrap_delete_ACE_MGMT_INSTALL_INFO_openace_035495a50e9dd2d9(ACE_MGMT_INSTALL_INFO *_swig_go_0) {
  ACE_MGMT_INSTALL_INFO *arg1 = (ACE_MGMT_INSTALL_INFO *) 0 ;
  
  arg1 = *(ACE_MGMT_INSTALL_INFO **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


intgo _wrap_SysSetTable_openace_035495a50e9dd2d9(intgo *_swig_go_0, intgo _swig_go_1, struct HB_ACEDATA *_swig_go_2, _gostring_ _swig_go_3) {
  ACE_HANDLE *arg1 = (ACE_HANDLE *) 0 ;
  HB_BOOL arg2 ;
  PHB_ACEDATA arg3 = (PHB_ACEDATA) 0 ;
  HB_UCHAR *arg4 = (HB_UCHAR *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = *(ACE_HANDLE **)&_swig_go_0; 
  arg2 = (HB_BOOL)_swig_go_1; 
  arg3 = *(PHB_ACEDATA *)&_swig_go_2; 
  
  arg4 = (HB_UCHAR *)malloc(_swig_go_3.n + 1);
  memcpy(arg4, _swig_go_3.p, _swig_go_3.n);
  arg4[_swig_go_3.n] = '\0';
  
  
  result = (HB_U32)ZwaSysSetTable(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  free(arg4); 
  return _swig_go_result;
}


intgo _wrap_SetCallbackOnRTE_openace_035495a50e9dd2d9(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (HB_U32)ZwaSetCallbackOnRTE(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_SetCallbackTrace_openace_035495a50e9dd2d9(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (HB_U32)ZwaSetCallbackTrace(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AddCustomKey_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaAddCustomKey(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AppendRecord_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaAppendRecord(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_ApplicationExit_openace_035495a50e9dd2d9() {
  HB_U32 result;
  intgo _swig_go_result;
  
  
  result = (HB_U32)ZwaApplicationExit();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AtBOF_openace_035495a50e9dd2d9(intgo _swig_go_0, short *_swig_go_1) {
  ACE_HANDLE arg1 ;
  HB_USHORT *arg2 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(HB_USHORT **)&_swig_go_1; 
  
  result = (HB_U32)ZwaAtBOF(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AtEOF_openace_035495a50e9dd2d9(intgo _swig_go_0, short *_swig_go_1) {
  ACE_HANDLE arg1 ;
  HB_USHORT *arg2 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(HB_USHORT **)&_swig_go_1; 
  
  result = (HB_U32)ZwaAtEOF(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CacheRecords_openace_035495a50e9dd2d9(intgo _swig_go_0, short _swig_go_1) {
  ACE_HANDLE arg1 ;
  HB_USHORT arg2 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = (HB_USHORT)_swig_go_1; 
  
  result = (HB_U32)ZwaCacheRecords(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_BeginTransaction_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaBeginTransaction(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_ClearFilter_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaClearFilter(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_ClearProgressCallback_openace_035495a50e9dd2d9() {
  HB_U32 result;
  intgo _swig_go_result;
  
  
  result = (HB_U32)ZwaClearProgressCallback();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_ClearRelation_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaClearRelation(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_ClearScope_openace_035495a50e9dd2d9(intgo _swig_go_0, short _swig_go_1) {
  ACE_HANDLE arg1 ;
  HB_USHORT arg2 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = (HB_USHORT)_swig_go_1; 
  
  result = (HB_U32)ZwaClearScope(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CloseAllIndexes_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaCloseAllIndexes(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CloseIndex_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaCloseIndex(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CloseTable_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaCloseTable(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CommitTransaction_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaCommitTransaction(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_Connect_openace_035495a50e9dd2d9(_gostring_ _swig_go_0, intgo *_swig_go_1) {
  HB_UCHAR *arg1 = (HB_UCHAR *) 0 ;
  ACE_HANDLE *arg2 = (ACE_HANDLE *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  
  arg1 = (HB_UCHAR *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  arg2 = *(ACE_HANDLE **)&_swig_go_1; 
  
  result = (HB_U32)ZwaConnect(arg1,arg2);
  _swig_go_result = result; 
  free(arg1); 
  return _swig_go_result;
}


intgo _wrap_CopyTableContents_openace_035495a50e9dd2d9(intgo _swig_go_0, intgo _swig_go_1, short _swig_go_2) {
  ACE_HANDLE arg1 ;
  ACE_HANDLE arg2 ;
  HB_USHORT arg3 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = (ACE_HANDLE)_swig_go_1; 
  arg3 = (HB_USHORT)_swig_go_2; 
  
  result = (HB_U32)ZwaCopyTableContents(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CreateIndex_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2, _gostring_ _swig_go_3, _gostring_ _swig_go_4, _gostring_ _swig_go_5, intgo _swig_go_6, intgo *_swig_go_7) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  HB_UCHAR *arg3 = (HB_UCHAR *) 0 ;
  HB_UCHAR *arg4 = (HB_UCHAR *) 0 ;
  HB_UCHAR *arg5 = (HB_UCHAR *) 0 ;
  HB_UCHAR *arg6 = (HB_UCHAR *) 0 ;
  HB_U32 arg7 ;
  ACE_HANDLE *arg8 = (ACE_HANDLE *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (HB_UCHAR *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  arg4 = (HB_UCHAR *)malloc(_swig_go_3.n + 1);
  memcpy(arg4, _swig_go_3.p, _swig_go_3.n);
  arg4[_swig_go_3.n] = '\0';
  
  
  arg5 = (HB_UCHAR *)malloc(_swig_go_4.n + 1);
  memcpy(arg5, _swig_go_4.p, _swig_go_4.n);
  arg5[_swig_go_4.n] = '\0';
  
  
  arg6 = (HB_UCHAR *)malloc(_swig_go_5.n + 1);
  memcpy(arg6, _swig_go_5.p, _swig_go_5.n);
  arg6[_swig_go_5.n] = '\0';
  
  arg7 = (HB_U32)_swig_go_6; 
  arg8 = *(ACE_HANDLE **)&_swig_go_7; 
  
  result = (HB_U32)ZwaCreateIndex(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  _swig_go_result = result; 
  free(arg2); 
  free(arg3); 
  free(arg4); 
  free(arg5); 
  free(arg6); 
  return _swig_go_result;
}


intgo _wrap_CreateTable_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2, short _swig_go_3, short _swig_go_4, short _swig_go_5, short _swig_go_6, short _swig_go_7, _gostring_ _swig_go_8, intgo *_swig_go_9) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  HB_UCHAR *arg3 = (HB_UCHAR *) 0 ;
  HB_USHORT arg4 ;
  HB_USHORT arg5 ;
  HB_USHORT arg6 ;
  HB_USHORT arg7 ;
  HB_USHORT arg8 ;
  HB_UCHAR *arg9 = (HB_UCHAR *) 0 ;
  ACE_HANDLE *arg10 = (ACE_HANDLE *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (HB_UCHAR *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  arg4 = (HB_USHORT)_swig_go_3; 
  arg5 = (HB_USHORT)_swig_go_4; 
  arg6 = (HB_USHORT)_swig_go_5; 
  arg7 = (HB_USHORT)_swig_go_6; 
  arg8 = (HB_USHORT)_swig_go_7; 
  
  arg9 = (HB_UCHAR *)malloc(_swig_go_8.n + 1);
  memcpy(arg9, _swig_go_8.p, _swig_go_8.n);
  arg9[_swig_go_8.n] = '\0';
  
  arg10 = *(ACE_HANDLE **)&_swig_go_9; 
  
  result = (HB_U32)ZwaCreateTable(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10);
  _swig_go_result = result; 
  free(arg2); 
  free(arg3); 
  free(arg9); 
  return _swig_go_result;
}


intgo _wrap_DeleteCustomKey_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaDeleteCustomKey(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_DeleteIndex_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaDeleteIndex(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_DeleteRecord_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaDeleteRecord(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_Disconnect_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaDisconnect(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_ExtractKey_openace_035495a50e9dd2d9(intgo _swig_go_0, ACE_UCHAR_OUT *_swig_go_1, short *_swig_go_2) {
  ACE_HANDLE arg1 ;
  ACE_UCHAR_OUT *arg2 = (ACE_UCHAR_OUT *) 0 ;
  HB_USHORT *arg3 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(ACE_UCHAR_OUT **)&_swig_go_1; 
  arg3 = *(HB_USHORT **)&_swig_go_2; 
  
  result = (HB_U32)ZwaExtractKey(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetAllIndexes_openace_035495a50e9dd2d9(intgo _swig_go_0, intgo *_swig_go_1, short *_swig_go_2) {
  ACE_HANDLE arg1 ;
  ACE_HANDLE *arg2 ;
  HB_USHORT *arg3 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(ACE_HANDLE **)&_swig_go_1; 
  arg3 = *(HB_USHORT **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetAllIndexes(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetAllLocks_openace_035495a50e9dd2d9(intgo _swig_go_0, intgo *_swig_go_1, short *_swig_go_2) {
  ACE_HANDLE arg1 ;
  HB_U32 *arg2 ;
  HB_USHORT *arg3 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(HB_U32 **)&_swig_go_1; 
  arg3 = *(HB_USHORT **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetAllLocks(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetBinary_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, intgo _swig_go_2, ACE_UCHAR_OUT *_swig_go_3, intgo *_swig_go_4) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  HB_U32 arg3 ;
  ACE_UCHAR_OUT *arg4 = (ACE_UCHAR_OUT *) 0 ;
  HB_U32 *arg5 = (HB_U32 *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (HB_U32)_swig_go_2; 
  arg4 = *(ACE_UCHAR_OUT **)&_swig_go_3; 
  arg5 = *(HB_U32 **)&_swig_go_4; 
  
  result = (HB_U32)ZwaGetBinary(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_GetBinaryLength_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, intgo *_swig_go_2) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  HB_U32 *arg3 = (HB_U32 *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = *(HB_U32 **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetBinaryLength(arg1,arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_GetDateFormat_openace_035495a50e9dd2d9(ACE_UCHAR_OUT *_swig_go_0, short *_swig_go_1) {
  ACE_UCHAR_OUT *arg1 = (ACE_UCHAR_OUT *) 0 ;
  HB_USHORT *arg2 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = *(ACE_UCHAR_OUT **)&_swig_go_0; 
  arg2 = *(HB_USHORT **)&_swig_go_1; 
  
  result = (HB_U32)ZwaGetDateFormat(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetDouble_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, double *_swig_go_2) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  double *arg3 = (double *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = *(double **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetDouble(arg1,arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_GetErrorString_openace_035495a50e9dd2d9(intgo _swig_go_0, ACE_UCHAR_OUT *_swig_go_1, short *_swig_go_2) {
  HB_U32 arg1 ;
  ACE_UCHAR_OUT *arg2 = (ACE_UCHAR_OUT *) 0 ;
  HB_USHORT *arg3 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (HB_U32)_swig_go_0; 
  arg2 = *(ACE_UCHAR_OUT **)&_swig_go_1; 
  arg3 = *(HB_USHORT **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetErrorString(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetField_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, ACE_UCHAR_OUT *_swig_go_2, intgo *_swig_go_3, short _swig_go_4) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  ACE_UCHAR_OUT *arg3 = (ACE_UCHAR_OUT *) 0 ;
  HB_U32 *arg4 = (HB_U32 *) 0 ;
  HB_USHORT arg5 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = *(ACE_UCHAR_OUT **)&_swig_go_2; 
  arg4 = *(HB_U32 **)&_swig_go_3; 
  arg5 = (HB_USHORT)_swig_go_4; 
  
  result = (HB_U32)ZwaGetField(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_GetFieldDecimals_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, short *_swig_go_2) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  HB_USHORT *arg3 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = *(HB_USHORT **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetFieldDecimals(arg1,arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_GetFieldLength_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, intgo *_swig_go_2) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  HB_U32 *arg3 = (HB_U32 *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = *(HB_U32 **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetFieldLength(arg1,arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_GetFieldName_openace_035495a50e9dd2d9(intgo _swig_go_0, short _swig_go_1, ACE_UCHAR_OUT *_swig_go_2, short *_swig_go_3) {
  ACE_HANDLE arg1 ;
  HB_USHORT arg2 ;
  ACE_UCHAR_OUT *arg3 = (ACE_UCHAR_OUT *) 0 ;
  HB_USHORT *arg4 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = (HB_USHORT)_swig_go_1; 
  arg3 = *(ACE_UCHAR_OUT **)&_swig_go_2; 
  arg4 = *(HB_USHORT **)&_swig_go_3; 
  
  result = (HB_U32)ZwaGetFieldName(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetFieldType_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, short *_swig_go_2) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  HB_USHORT *arg3 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = *(HB_USHORT **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetFieldType(arg1,arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_GetHandleType_openace_035495a50e9dd2d9(intgo _swig_go_0, short *_swig_go_1) {
  ACE_HANDLE arg1 ;
  HB_USHORT *arg2 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(HB_USHORT **)&_swig_go_1; 
  
  result = (HB_U32)ZwaGetHandleType(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetIndexCondition_openace_035495a50e9dd2d9(intgo _swig_go_0, ACE_UCHAR_OUT *_swig_go_1, short *_swig_go_2) {
  ACE_HANDLE arg1 ;
  ACE_UCHAR_OUT *arg2 = (ACE_UCHAR_OUT *) 0 ;
  HB_USHORT *arg3 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(ACE_UCHAR_OUT **)&_swig_go_1; 
  arg3 = *(HB_USHORT **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetIndexCondition(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetIndexExpr_openace_035495a50e9dd2d9(intgo _swig_go_0, ACE_UCHAR_OUT *_swig_go_1, short *_swig_go_2) {
  ACE_HANDLE arg1 ;
  ACE_UCHAR_OUT *arg2 = (ACE_UCHAR_OUT *) 0 ;
  HB_USHORT *arg3 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(ACE_UCHAR_OUT **)&_swig_go_1; 
  arg3 = *(HB_USHORT **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetIndexExpr(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetIndexFilename_openace_035495a50e9dd2d9(intgo _swig_go_0, short _swig_go_1, ACE_UCHAR_OUT *_swig_go_2, short *_swig_go_3) {
  ACE_HANDLE arg1 ;
  HB_USHORT arg2 ;
  ACE_UCHAR_OUT *arg3 = (ACE_UCHAR_OUT *) 0 ;
  HB_USHORT *arg4 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = (HB_USHORT)_swig_go_1; 
  arg3 = *(ACE_UCHAR_OUT **)&_swig_go_2; 
  arg4 = *(HB_USHORT **)&_swig_go_3; 
  
  result = (HB_U32)ZwaGetIndexFilename(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetIndexName_openace_035495a50e9dd2d9(intgo _swig_go_0, ACE_UCHAR_OUT *_swig_go_1, short *_swig_go_2) {
  ACE_HANDLE arg1 ;
  ACE_UCHAR_OUT *arg2 = (ACE_UCHAR_OUT *) 0 ;
  HB_USHORT *arg3 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(ACE_UCHAR_OUT **)&_swig_go_1; 
  arg3 = *(HB_USHORT **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetIndexName(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetIndexHandle_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, intgo *_swig_go_2) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  ACE_HANDLE *arg3 = (ACE_HANDLE *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = *(ACE_HANDLE **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetIndexHandle(arg1,arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_GetIndexHandleByOrder_openace_035495a50e9dd2d9(intgo _swig_go_0, short _swig_go_1, intgo *_swig_go_2) {
  ACE_HANDLE arg1 ;
  HB_USHORT arg2 ;
  ACE_HANDLE *arg3 = (ACE_HANDLE *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = (HB_USHORT)_swig_go_1; 
  arg3 = *(ACE_HANDLE **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetIndexHandleByOrder(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetJulian_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, intgo *_swig_go_2) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  HB_I32 *arg3 = (HB_I32 *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = *(HB_I32 **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetJulian(arg1,arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_GetKeyCount_openace_035495a50e9dd2d9(intgo _swig_go_0, short _swig_go_1, intgo *_swig_go_2) {
  ACE_HANDLE arg1 ;
  HB_USHORT arg2 ;
  HB_U32 *arg3 = (HB_U32 *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = (HB_USHORT)_swig_go_1; 
  arg3 = *(HB_U32 **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetKeyCount(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetKeyLength_openace_035495a50e9dd2d9(intgo _swig_go_0, short *_swig_go_1) {
  ACE_HANDLE arg1 ;
  HB_USHORT *arg2 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(HB_USHORT **)&_swig_go_1; 
  
  result = (HB_U32)ZwaGetKeyLength(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetKeyNum_openace_035495a50e9dd2d9(intgo _swig_go_0, short _swig_go_1, intgo *_swig_go_2) {
  ACE_HANDLE arg1 ;
  HB_USHORT arg2 ;
  HB_U32 *arg3 = (HB_U32 *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = (HB_USHORT)_swig_go_1; 
  arg3 = *(HB_U32 **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetKeyNum(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetKeyType_openace_035495a50e9dd2d9(intgo _swig_go_0, short *_swig_go_1) {
  ACE_HANDLE arg1 ;
  HB_USHORT *arg2 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(HB_USHORT **)&_swig_go_1; 
  
  result = (HB_U32)ZwaGetKeyType(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetLastError_openace_035495a50e9dd2d9(intgo *_swig_go_0, ACE_UCHAR_OUT *_swig_go_1, short *_swig_go_2) {
  HB_U32 *arg1 = (HB_U32 *) 0 ;
  ACE_UCHAR_OUT *arg2 = (ACE_UCHAR_OUT *) 0 ;
  HB_USHORT *arg3 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = *(HB_U32 **)&_swig_go_0; 
  arg2 = *(ACE_UCHAR_OUT **)&_swig_go_1; 
  arg3 = *(HB_USHORT **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetLastError(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetLastTableUpdate_openace_035495a50e9dd2d9(intgo _swig_go_0, ACE_UCHAR_OUT *_swig_go_1, short *_swig_go_2) {
  ACE_HANDLE arg1 ;
  ACE_UCHAR_OUT *arg2 = (ACE_UCHAR_OUT *) 0 ;
  HB_USHORT *arg3 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(ACE_UCHAR_OUT **)&_swig_go_1; 
  arg3 = *(HB_USHORT **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetLastTableUpdate(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetLogical_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, short *_swig_go_2) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  HB_USHORT *arg3 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = *(HB_USHORT **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetLogical(arg1,arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_GetMemoLength_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, intgo *_swig_go_2) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  HB_U32 *arg3 = (HB_U32 *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = *(HB_U32 **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetMemoLength(arg1,arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_GetMilliseconds_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, intgo *_swig_go_2) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  HB_I32 *arg3 = (HB_I32 *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = *(HB_I32 **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetMilliseconds(arg1,arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_GetNumFields_openace_035495a50e9dd2d9(intgo _swig_go_0, short *_swig_go_1) {
  ACE_HANDLE arg1 ;
  HB_USHORT *arg2 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(HB_USHORT **)&_swig_go_1; 
  
  result = (HB_U32)ZwaGetNumFields(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetNumIndexes_openace_035495a50e9dd2d9(intgo _swig_go_0, short *_swig_go_1) {
  ACE_HANDLE arg1 ;
  HB_USHORT *arg2 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(HB_USHORT **)&_swig_go_1; 
  
  result = (HB_U32)ZwaGetNumIndexes(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetNumLocks_openace_035495a50e9dd2d9(intgo _swig_go_0, short *_swig_go_1) {
  ACE_HANDLE arg1 ;
  HB_USHORT *arg2 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(HB_USHORT **)&_swig_go_1; 
  
  result = (HB_U32)ZwaGetNumLocks(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetRecordCount_openace_035495a50e9dd2d9(intgo _swig_go_0, short _swig_go_1, intgo *_swig_go_2) {
  ACE_HANDLE arg1 ;
  HB_USHORT arg2 ;
  HB_U32 *arg3 = (HB_U32 *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = (HB_USHORT)_swig_go_1; 
  arg3 = *(HB_U32 **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetRecordCount(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetRecordNum_openace_035495a50e9dd2d9(intgo _swig_go_0, short _swig_go_1, intgo *_swig_go_2) {
  ACE_HANDLE arg1 ;
  HB_USHORT arg2 ;
  HB_U32 *arg3 = (HB_U32 *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = (HB_USHORT)_swig_go_1; 
  arg3 = *(HB_U32 **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetRecordNum(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetRecordLength_openace_035495a50e9dd2d9(intgo _swig_go_0, intgo *_swig_go_1) {
  ACE_HANDLE arg1 ;
  HB_U32 *arg2 = (HB_U32 *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(HB_U32 **)&_swig_go_1; 
  
  result = (HB_U32)ZwaGetRecordLength(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetRelKeyPos_openace_035495a50e9dd2d9(intgo _swig_go_0, double *_swig_go_1) {
  ACE_HANDLE arg1 ;
  double *arg2 = (double *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(double **)&_swig_go_1; 
  
  result = (HB_U32)ZwaGetRelKeyPos(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetServerName_openace_035495a50e9dd2d9(intgo _swig_go_0, ACE_UCHAR_OUT *_swig_go_1, short *_swig_go_2) {
  ACE_HANDLE arg1 ;
  ACE_UCHAR_OUT *arg2 = (ACE_UCHAR_OUT *) 0 ;
  HB_USHORT *arg3 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(ACE_UCHAR_OUT **)&_swig_go_1; 
  arg3 = *(HB_USHORT **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetServerName(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetString_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, ACE_UCHAR_OUT *_swig_go_2, intgo *_swig_go_3, short _swig_go_4) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  ACE_UCHAR_OUT *arg3 = (ACE_UCHAR_OUT *) 0 ;
  HB_U32 *arg4 = (HB_U32 *) 0 ;
  HB_USHORT arg5 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = *(ACE_UCHAR_OUT **)&_swig_go_2; 
  arg4 = *(HB_U32 **)&_swig_go_3; 
  arg5 = (HB_USHORT)_swig_go_4; 
  
  result = (HB_U32)ZwaGetString(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_GetTableAlias_openace_035495a50e9dd2d9(intgo _swig_go_0, ACE_UCHAR_OUT *_swig_go_1, short *_swig_go_2) {
  ACE_HANDLE arg1 ;
  ACE_UCHAR_OUT *arg2 = (ACE_UCHAR_OUT *) 0 ;
  HB_USHORT *arg3 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(ACE_UCHAR_OUT **)&_swig_go_1; 
  arg3 = *(HB_USHORT **)&_swig_go_2; 
  
  result = (HB_U32)ZwaGetTableAlias(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetTableFilename_openace_035495a50e9dd2d9(intgo _swig_go_0, short _swig_go_1, ACE_UCHAR_OUT *_swig_go_2, short *_swig_go_3) {
  ACE_HANDLE arg1 ;
  HB_USHORT arg2 ;
  ACE_UCHAR_OUT *arg3 = (ACE_UCHAR_OUT *) 0 ;
  HB_USHORT *arg4 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = (HB_USHORT)_swig_go_1; 
  arg3 = *(ACE_UCHAR_OUT **)&_swig_go_2; 
  arg4 = *(HB_USHORT **)&_swig_go_3; 
  
  result = (HB_U32)ZwaGetTableFilename(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GetTableType_openace_035495a50e9dd2d9(intgo _swig_go_0, short *_swig_go_1) {
  ACE_HANDLE arg1 ;
  HB_USHORT *arg2 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(HB_USHORT **)&_swig_go_1; 
  
  result = (HB_U32)ZwaGetTableType(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GotoBottom_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaGotoBottom(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GotoRecord_openace_035495a50e9dd2d9(intgo _swig_go_0, intgo _swig_go_1) {
  ACE_HANDLE arg1 ;
  HB_U32 arg2 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = (HB_U32)_swig_go_1; 
  
  result = (HB_U32)ZwaGotoRecord(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GotoTop_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaGotoTop(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_IsEmpty_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, short *_swig_go_2) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  HB_USHORT *arg3 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = *(HB_USHORT **)&_swig_go_2; 
  
  result = (HB_U32)ZwaIsEmpty(arg1,arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_IsIndexDescending_openace_035495a50e9dd2d9(intgo _swig_go_0, short *_swig_go_1) {
  ACE_HANDLE arg1 ;
  HB_USHORT *arg2 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(HB_USHORT **)&_swig_go_1; 
  
  result = (HB_U32)ZwaIsIndexDescending(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_IsIndexUnique_openace_035495a50e9dd2d9(intgo _swig_go_0, short *_swig_go_1) {
  ACE_HANDLE arg1 ;
  HB_USHORT *arg2 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(HB_USHORT **)&_swig_go_1; 
  
  result = (HB_U32)ZwaIsIndexUnique(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_IsRecordDeleted_openace_035495a50e9dd2d9(intgo _swig_go_0, short *_swig_go_1) {
  ACE_HANDLE arg1 ;
  HB_USHORT *arg2 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(HB_USHORT **)&_swig_go_1; 
  
  result = (HB_U32)ZwaIsRecordDeleted(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LockRecord_openace_035495a50e9dd2d9(intgo _swig_go_0, intgo _swig_go_1) {
  ACE_HANDLE arg1 ;
  HB_U32 arg2 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = (HB_U32)_swig_go_1; 
  
  result = (HB_U32)ZwaLockRecord(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LockTable_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaLockTable(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_MgConnect_openace_035495a50e9dd2d9(_gostring_ _swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2, intgo *_swig_go_3) {
  HB_UCHAR *arg1 = (HB_UCHAR *) 0 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  HB_UCHAR *arg3 = (HB_UCHAR *) 0 ;
  ACE_HANDLE *arg4 = (ACE_HANDLE *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  
  arg1 = (HB_UCHAR *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (HB_UCHAR *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  arg4 = *(ACE_HANDLE **)&_swig_go_3; 
  
  result = (HB_U32)ZwaMgConnect(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  free(arg1); 
  free(arg2); 
  free(arg3); 
  return _swig_go_result;
}


intgo _wrap_MgDisconnect_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaMgDisconnect(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_MgGetInstallInfo_openace_035495a50e9dd2d9(intgo _swig_go_0, ACE_MGMT_INSTALL_INFO *_swig_go_1, short *_swig_go_2) {
  ACE_HANDLE arg1 ;
  ACE_MGMT_INSTALL_INFO *arg2 = (ACE_MGMT_INSTALL_INFO *) 0 ;
  HB_USHORT *arg3 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(ACE_MGMT_INSTALL_INFO **)&_swig_go_1; 
  arg3 = *(HB_USHORT **)&_swig_go_2; 
  
  result = (HB_U32)ZwaMgGetInstallInfo(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_MgGetServerType_openace_035495a50e9dd2d9(intgo _swig_go_0, short *_swig_go_1) {
  ACE_HANDLE arg1 ;
  HB_USHORT *arg2 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = *(HB_USHORT **)&_swig_go_1; 
  
  result = (HB_U32)ZwaMgGetServerType(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_NullTerminateStrings_openace_035495a50e9dd2d9(short _swig_go_0) {
  HB_USHORT arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (HB_USHORT)_swig_go_0; 
  
  result = (HB_U32)ZwaNullTerminateStrings(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_OpenIndex_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, intgo *_swig_go_2, short *_swig_go_3) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  ACE_HANDLE *arg3 ;
  HB_USHORT *arg4 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = *(ACE_HANDLE **)&_swig_go_2; 
  arg4 = *(HB_USHORT **)&_swig_go_3; 
  
  result = (HB_U32)ZwaOpenIndex(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_OpenTable_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2, short _swig_go_3, short _swig_go_4, short _swig_go_5, short _swig_go_6, intgo _swig_go_7, intgo *_swig_go_8) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  HB_UCHAR *arg3 = (HB_UCHAR *) 0 ;
  HB_USHORT arg4 ;
  HB_USHORT arg5 ;
  HB_USHORT arg6 ;
  HB_USHORT arg7 ;
  HB_U32 arg8 ;
  ACE_HANDLE *arg9 = (ACE_HANDLE *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (HB_UCHAR *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  arg4 = (HB_USHORT)_swig_go_3; 
  arg5 = (HB_USHORT)_swig_go_4; 
  arg6 = (HB_USHORT)_swig_go_5; 
  arg7 = (HB_USHORT)_swig_go_6; 
  arg8 = (HB_U32)_swig_go_7; 
  arg9 = *(ACE_HANDLE **)&_swig_go_8; 
  
  result = (HB_U32)ZwaOpenTable(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9);
  _swig_go_result = result; 
  free(arg2); 
  free(arg3); 
  return _swig_go_result;
}


intgo _wrap_PackTable_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaPackTable(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_RecallRecord_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaRecallRecord(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_RefreshRecord_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaRefreshRecord(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_Reindex_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaReindex(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_RollbackTransaction_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaRollbackTransaction(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_Seek_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, short _swig_go_2, short _swig_go_3, short _swig_go_4, short *_swig_go_5) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  HB_USHORT arg3 ;
  HB_USHORT arg4 ;
  HB_USHORT arg5 ;
  HB_USHORT *arg6 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (HB_USHORT)_swig_go_2; 
  arg4 = (HB_USHORT)_swig_go_3; 
  arg5 = (HB_USHORT)_swig_go_4; 
  arg6 = *(HB_USHORT **)&_swig_go_5; 
  
  result = (HB_U32)ZwaSeek(arg1,arg2,arg3,arg4,arg5,arg6);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_SeekLast_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, short _swig_go_2, short _swig_go_3, short *_swig_go_4) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  HB_USHORT arg3 ;
  HB_USHORT arg4 ;
  HB_USHORT *arg5 = (HB_USHORT *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (HB_USHORT)_swig_go_2; 
  arg4 = (HB_USHORT)_swig_go_3; 
  arg5 = *(HB_USHORT **)&_swig_go_4; 
  
  result = (HB_U32)ZwaSeekLast(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_SetDateFormat_openace_035495a50e9dd2d9(_gostring_ _swig_go_0) {
  HB_UCHAR *arg1 = (HB_UCHAR *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  
  arg1 = (HB_UCHAR *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  result = (HB_U32)ZwaSetDateFormat(arg1);
  _swig_go_result = result; 
  free(arg1); 
  return _swig_go_result;
}


intgo _wrap_SetDefault_openace_035495a50e9dd2d9(_gostring_ _swig_go_0) {
  HB_UCHAR *arg1 = (HB_UCHAR *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  
  arg1 = (HB_UCHAR *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  result = (HB_U32)ZwaSetDefault(arg1);
  _swig_go_result = result; 
  free(arg1); 
  return _swig_go_result;
}


intgo _wrap_SetDouble_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, double _swig_go_2) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  double arg3 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (double)_swig_go_2; 
  
  result = (HB_U32)ZwaSetDouble(arg1,arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_SetEmpty_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (HB_U32)ZwaSetEmpty(arg1,arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_SetField_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2, intgo _swig_go_3) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  HB_UCHAR *arg3 = (HB_UCHAR *) 0 ;
  HB_U32 arg4 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (HB_UCHAR *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  arg4 = (HB_U32)_swig_go_3; 
  
  result = (HB_U32)ZwaSetField(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  free(arg2); 
  free(arg3); 
  return _swig_go_result;
}


intgo _wrap_SetFilter_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (HB_U32)ZwaSetFilter(arg1,arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_SetJulian_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, intgo _swig_go_2) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  HB_I32 arg3 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (HB_I32)_swig_go_2; 
  
  result = (HB_U32)ZwaSetJulian(arg1,arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_SetLogical_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, short _swig_go_2) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  HB_USHORT arg3 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (HB_USHORT)_swig_go_2; 
  
  result = (HB_U32)ZwaSetLogical(arg1,arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_SetMilliseconds_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, intgo _swig_go_2) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  HB_I32 arg3 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (HB_I32)_swig_go_2; 
  
  result = (HB_U32)ZwaSetMilliseconds(arg1,arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_SetRelKeyPos_openace_035495a50e9dd2d9(intgo _swig_go_0, double _swig_go_1) {
  ACE_HANDLE arg1 ;
  double arg2 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  result = (HB_U32)ZwaSetRelKeyPos(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_SetSearchPath_openace_035495a50e9dd2d9(_gostring_ _swig_go_0) {
  HB_UCHAR *arg1 = (HB_UCHAR *) 0 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  
  arg1 = (HB_UCHAR *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  result = (HB_U32)ZwaSetSearchPath(arg1);
  _swig_go_result = result; 
  free(arg1); 
  return _swig_go_result;
}


intgo _wrap_SetString_openace_035495a50e9dd2d9(intgo _swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2, intgo _swig_go_3) {
  ACE_HANDLE arg1 ;
  HB_UCHAR *arg2 = (HB_UCHAR *) 0 ;
  HB_UCHAR *arg3 = (HB_UCHAR *) 0 ;
  HB_U32 arg4 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  arg2 = (HB_UCHAR *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (HB_UCHAR *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  arg4 = (HB_U32)_swig_go_3; 
  
  result = (HB_U32)ZwaSetString(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  free(arg2); 
  free(arg3); 
  return _swig_go_result;
}


intgo _wrap_ShowDeleted_openace_035495a50e9dd2d9(short _swig_go_0) {
  HB_USHORT arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (HB_USHORT)_swig_go_0; 
  
  result = (HB_U32)ZwaShowDeleted(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_Skip_openace_035495a50e9dd2d9(intgo _swig_go_0, intgo _swig_go_1) {
  ACE_HANDLE arg1 ;
  HB_I32 arg2 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = (HB_I32)_swig_go_1; 
  
  result = (HB_U32)ZwaSkip(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_UnlockRecord_openace_035495a50e9dd2d9(intgo _swig_go_0, intgo _swig_go_1) {
  ACE_HANDLE arg1 ;
  HB_U32 arg2 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  arg2 = (HB_U32)_swig_go_1; 
  
  result = (HB_U32)ZwaUnlockRecord(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_UnlockTable_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaUnlockTable(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_WriteRecord_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaWriteRecord(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_ZapTable_openace_035495a50e9dd2d9(intgo _swig_go_0) {
  ACE_HANDLE arg1 ;
  HB_U32 result;
  intgo _swig_go_result;
  
  arg1 = (ACE_HANDLE)_swig_go_0; 
  
  result = (HB_U32)ZwaZapTable(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


#ifdef __cplusplus
}
#endif

